### ISSUE TITLE
Build error in v5.0 and master branches

### ISSUE THREAD

**Issue by kurapatijayaram** [open-webrtc-toolkit/owt-server#1018]
Hi,
I tried to build the code but when I execute `scripts/build.js -t all --check` I am getting following error.

```
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
internalIO.target.mk:133: recipe for target 'Release/obj.target/internalIO/../../../core/owt_base/RawTransport.o' failed
make: *** [Release/obj.target/internalIO/../../../core/owt_base/RawTransport.o] Error 4
make: *** Waiting for unfinished jobs....
make: Leaving directory '/owt-server/source/agent/addons/internalIO/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v10.21.0/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.10.25-linuxkit
gyp ERR! command "/root/.nvm/versions/node/v10.21.0/bin/node" "/root/.nvm/versions/node/v10.21.0/bin/node-gyp" "build" "-j" "6" "--loglevel=error"
gyp ERR! cwd /owt-server/source/agent/addons/internalIO
gyp ERR! node -v v10.21.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
child_process.js:669
    throw err;
    ^

Error: Command failed: node-gyp build -j 6 --loglevel=error
    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at buildTarget (/owt-server/scripts/build.js:147:5)
    at buildList.map (/owt-server/scripts/build.js:175:10)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/owt-server/scripts/build.js:170:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

```

Please help me.
Thank you.

**Comment by kurapatijayaram** [comment]
Hi @jianjunz , @starwarfan , can you guys pls help me on this.

Thank you.

**Comment by Alex-YddeR** [comment]
What is the OS you are working on, it works for me with the latest master branch with out any issues

You may need to use as below, since **scripts/build.js -t all --check** works with GPU accelerated if enabled.

scripts/build.js -t mcu --check

Thanks

**Comment by kurapatijayaram** [comment]
Hi @Alex-YddeR ,
Thanks for the reply. I am using Ubuntu 18.04.
Today I pulled the latest master branch and executed `scripts/build.js -t mcu --check`, then following error got triggered

```
/owt-server/build/libdeps/build/lib/pkgconfig:/owt-server/build/libdeps/build/lib64/pkgconfig:
Following targets will be built:
 video-mixer-sw 
 video-transcoder-sw 
 video-analyzer-sw 
 internal-io 
 logger 
 media-frame-multicaster 
 audio 
 audio-ranker 
 webrtc-conn 
 webrtc-frame 
 avstream 
 gst-pipeline 
 sip 
Building addon - video-mixer-sw
make: Entering directory '/owt-server/source/agent/video/videoMixer/videoMixer_sw/build'
  CXX(target) Release/obj.target/videoMixer-sw/../addon.o
  CXX(target) Release/obj.target/videoMixer-sw/../VideoMixerWrapper.o
  CXX(target) Release/obj.target/videoMixer-sw/../SoftVideoCompositor.o
  CXX(target) Release/obj.target/videoMixer-sw/../VideoMixer.o
  CXX(target) Release/obj.target/videoMixer-sw/../../../../core/owt_base/MediaFramePipeline.o
  CXX(target) Release/obj.target/videoMixer-sw/../../../../core/owt_base/FrameConverter.o
../../../../../core/owt_base/FrameConverter.cpp:7:10: fatal error: libyuv/convert.h: No such file or directory
 #include <libyuv/convert.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
videoMixer-sw.target.mk:142: recipe for target 'Release/obj.target/videoMixer-sw/../../../../core/owt_base/FrameConverter.o' failed
make: *** [Release/obj.target/videoMixer-sw/../../../../core/owt_base/FrameConverter.o] Error 1
make: *** Waiting for unfinished jobs....
../../SoftVideoCompositor.cpp:7:10: fatal error: libyuv/convert.h: No such file or directory
 #include "libyuv/convert.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
videoMixer-sw.target.mk:142: recipe for target 'Release/obj.target/videoMixer-sw/../SoftVideoCompositor.o' failed
make: *** [Release/obj.target/videoMixer-sw/../SoftVideoCompositor.o] Error 1
make: Leaving directory '/owt-server/source/agent/video/videoMixer/videoMixer_sw/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v10.21.0/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.10.25-linuxkit
gyp ERR! command "/root/.nvm/versions/node/v10.21.0/bin/node" "/root/.nvm/versions/node/v10.21.0/bin/node-gyp" "build" "-j" "6" "--loglevel=error"
gyp ERR! cwd /owt-server/source/agent/video/videoMixer/videoMixer_sw
gyp ERR! node -v v10.21.0
gyp ERR! node-gyp -v v8.1.0
gyp ERR! not ok 
child_process.js:669
    throw err;
    ^

Error: Command failed: node-gyp build -j 6 --loglevel=error
    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at buildTarget (/owt-server/scripts/build.js:147:5)
    at buildList.map (/owt-server/scripts/build.js:175:10)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/owt-server/scripts/build.js:170:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

```

Please help me if you aware of this.

Thank you.

**Comment by kurapatijayaram** [comment]
I tried docker also it didnt worked. here is the error when I build using docker:

```
#8 8.655 2021-07-02 05:25:03 (2.70 MB/s) - written to stdout [950538]
#8 8.655 
#8 8.668 patching file agent/agent-priv.h
#8 8.669 patching file agent/agent.c
#8 8.670 patching file agent/conncheck.c
#8 8.670 patching file agent/discovery.c
#8 8.670 patching file socket/tcp-bsd.c
#8 8.671 patching file socket/tcp-bsd.h
#8 8.671 patching file socket/turn.c
#8 8.671 patching file socket/turn.h
#8 8.674 patching file agent/agent.c
#8 8.675 patching file agent/agent.h
#8 8.675 patching file agent/conncheck.c
#8 8.676 patching file nice/libnice.sym
#8 8.678 patching file agent/agent.c
#8 8.678 patching file agent/agent.h
#8 8.679 patching file nice/libnice.sym
#8 8.681 patching file agent/conncheck.c
#8 8.683 patching file agent/agent.c
#8 8.683 patching file agent/component.c
#8 8.683 patching file agent/component.h
#8 8.684 patching file agent/conncheck.c
#8 8.686 /bin/sh: 1: cannot open owt-server-4.3/scripts/patches/libnice014-closelock.patch: No such file
------
executor failed running [/bin/sh -c wget -O - ${NICE_REPO} | tar xz &&     cd libnice-${NICE_VER} &&     wget -O - ${LIBNICE_PATCH_REPO} | tar xz  &&     patch -p1 < owt-server-${LIBNICE_PATCH_VER}/scripts/patches/libnice014-agentlock.patch &&     patch -p1 < owt-server-${LIBNICE_PATCH_VER}/scripts/patches/libnice014-agentlock-plus.patch &&     patch -p1 < owt-server-${LIBNICE_PATCH_VER}/scripts/patches/libnice014-removecandidate.patch &&     patch -p1 < owt-server-${LIBNICE_PATCH_VER}/scripts/patches/libnice014-keepalive.patch &&     patch -p1 < owt-server-${LIBNICE_PATCH_VER}/scripts/patches/libnice014-startcheck.patch &&     patch -p1 < owt-server-${LIBNICE_PATCH_VER}/scripts/patches/libnice014-closelock.patch &&     ./configure --prefix="/usr/local" --libdir=/usr/local/lib/x86_64-linux-gnu &&     make -s V=0 &&     make install]: exit code: 2
```

**Comment by Alex-YddeR** [comment]
I am using below release

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

Just follow below steps in fresh ubuntu

    1  sudo apt-get update
    2  git clone https://github.com/open-webrtc-toolkit/owt-server.git
    3  cd owt-server/
    4  scripts/installDeps.sh
    5  scripts/build.js -t mcu --check .

Thanks
Alex

**Comment by kurapatijayaram** [comment]
In the latest build I am unable to install deps also, I am getting following error:

`scripts/installDeps.sh: line 103: install_mediadeps: command not found`

**Comment by kurapatijayaram** [comment]
Hi @Alex-YddeR ,
Previously I used to install quic dependencies also, now I skipped that and I tried to build then I received g++ related error :

```
/root/.cache/node-gyp/10.21.0/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
../InternalConfig.cc: In function 'void setPassphrase(const v8::FunctionCallbackInfo<v8::Value>&)':
../InternalConfig.cc:15:47: warning: 'v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)' is deprecated: Use Isolate version [-Wdeprecated-declarations]
   String::Utf8Value param0(args[0]->ToString());
                                               ^
In file included from /root/.cache/node-gyp/10.21.0/include/node/v8.h:26:0,
                 from /root/.cache/node-gyp/10.21.0/include/node/node.h:63,
                 from ../InternalConfig.h:8,
                 from ../InternalConfig.cc:9:
/root/.cache/node-gyp/10.21.0/include/node/v8.h:2892:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/root/.cache/node-gyp/10.21.0/include/node/v8config.h:324:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
internalIO.target.mk:128: recipe for target 'Release/obj.target/internalIO/InternalIOWrapper.o' failed
make: *** [Release/obj.target/internalIO/InternalIOWrapper.o] Error 4
make: *** Waiting for unfinished jobs....
make: Leaving directory '/owt-server/source/agent/addons/internalIO/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v10.21.0/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.10.25-linuxkit
gyp ERR! command "/root/.nvm/versions/node/v10.21.0/bin/node" "/root/.nvm/versions/node/v10.21.0/bin/node-gyp" "build" "-j" "6" "--loglevel=error"
gyp ERR! cwd /owt-server/source/agent/addons/internalIO
gyp ERR! node -v v10.21.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
child_process.js:669
    throw err;
    ^

Error: Command failed: node-gyp build -j 6 --loglevel=error
    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at buildTarget (/owt-server/scripts/build.js:133:5)
    at buildList.map (/owt-server/scripts/build.js:161:10)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/owt-server/scripts/build.js:156:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
```

Please help me if you are aware of this.

Thank you.

**Comment by kurapatijayaram** [comment]
Can someone help me on this. 
@starwarfan  @jianjunz 

Thank you.

**Comment by starwarfan** [comment]
Hi,
`g++: internal compiler error: Killed (program cc1plus)`.
This looks like you compilation aborts due to out of memory.

**Comment by kurapatijayaram** [comment]
Thank you so much @starwarfan and @Alex-YddeR  , It worked. 👍 (without quic)
