### ISSUE TITLE
owt in docker fails to start Portal.

### ISSUE THREAD

**Issue by richard-romano** [open-webrtc-toolkit/owt-server#1080]
OS: Ubuntu
System: An i7 NUC - Intel NUC8i7BEH
Repo: owt-server 5.0.x
Installation: Used the unmodified build_docker_image.sh script following the docker/README.md
Mongo/Rabbit: I've tried with both running as services within the container and both running on host with same issue.

Issue: The portal fails to start and appears to have issues accessing mongo. I've rebuilt the docker images/containers quite a few times and tried putting mongo in various spots. If I'm in the container I can use mongo just fine, only owt seems to have an issue.

stdout files with errors in them. The logs files don't appear to have any errors.

**app.stdout**
getRooms failed( 500 ): {"error":{"code":2001,"message":"MongooseError Operation `services.findOne()` buffering timed out after 10000ms"}}

**portal.stdout**
2021-09-03 17:08:45.518  - DEBUG: AmqpClient - Connect OK
2021-09-03 17:08:45.524  - DEBUG: AmqpClient - Start consume amq.gen-ONriYbGyMh11BehANFr1yQ owtRpc
2021-09-03 17:08:45.524  - INFO: Main - portal initializing as rpc client ok
2021-09-03 17:08:45.528  - DEBUG: ClusterWorker - Try joining cluster owt-cluster , retry count: 0
2021-09-03 17:08:45.528  - DEBUG: AmqpClient - remoteCall, corrID: 0 to: owt-cluster method: join
2021-09-03 17:08:45.529  - DEBUG: AmqpClient - Publish content: {"method":"join","args":["portal","portal-d3ad3e0e9b13213322e4@172.16.15.48",{"ip":"172.16.15.48","hostname":"","port":8080,"via_host":"","ssl":true,"state":2,"max_load":0.85,"capacity":{"isps":[],"regions":[]}}],"corrID":0,"replyTo":"amq.gen-ONriYbGyMh11BehANFr1yQ"}
2021-09-03 17:08:45.531  - DEBUG: AmqpClient - New message received { data: 'in-service', corrID: 0, type: 'callback' }
2021-09-03 17:08:45.532  - DEBUG: AmqpClient - Callback callback  -  in-service
2021-09-03 17:08:45.532  - INFO: Main - portal join cluster ok, with rpcID: portal-d3ad3e0e9b13213322e4@172.16.15.48
2021-09-03 17:08:45.533  - INFO: ClusterWorker - Join cluster owt-cluster OK.
2021-09-03 17:08:45.535  - DEBUG: AmqpClient - Setup rpc server ok: portal-d3ad3e0e9b13213322e4@172.16.15.48
2021-09-03 17:08:45.535  - INFO: Main - portal initializing as rpc server ok
2021-09-03 17:08:45.538  - INFO: Main - portal-d3ad3e0e9b13213322e4@172.16.15.48 as monitor ready
2021-09-03 17:08:45.765  - INFO: Main - Failed to get token key. err: null
2021-09-03 17:08:45.765  - ERROR: Main - portal getting token failed.
2021-09-03 17:08:45.765  - INFO: LoadCollector - To stop load collector.
2021-09-03 17:08:45.765  - DEBUG: LoadCollector - To stop cpu load collector.
2021-09-03 17:08:45.765  - INFO: Main - Process exit

**management-api.stdout**
2021-09-03 17:08:33.215  - INFO: ManagementServer - Worker 19566 started
2021-09-03 17:08:33.236  - DEBUG: AmqpClient - Connect OK
2021-09-03 17:08:33.236  - INFO: ManagementServer - Worker 19567 started
2021-09-03 17:08:33.243  - DEBUG: AmqpClient - Start consume amq.gen-BNa3WmYmRP2X9qAdcK6Rsg owtRpc
2021-09-03 17:08:33.265  - DEBUG: AmqpClient - Connect OK
2021-09-03 17:08:33.274  - DEBUG: AmqpClient - Start consume amq.gen-aqzdY_ado7xLZ-Yco0OPyQ owtRpc
2021-09-03 17:08:33.294  - INFO: ManagementServer - Worker 19580 started
2021-09-03 17:08:33.300  - INFO: ManagementServer - Worker 19573 started
2021-09-03 17:08:33.315  - DEBUG: AmqpClient - Connect OK
2021-09-03 17:08:33.321  - DEBUG: AmqpClient - Start consume amq.gen-Y8G8a4Se4Wvlh544xwWpiw owtRpc
2021-09-03 17:08:33.322  - DEBUG: AmqpClient - Connect OK
2021-09-03 17:08:33.328  - DEBUG: AmqpClient - Start consume amq.gen-nkHZVAu5hGyctzIfoCMK6A owtRpc
Save serverKey error: MongooseError: Operation `keys.findOneAndUpdate()` buffering timed out after 10000ms
    at Timeout.setTimeout (/home/owt/management_api/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:198:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
2021-09-03 17:08:56.679  - WARN: ManagementServer - MongooseError: Operation `services.findOne()` buffering timed out after 10000ms
    at Timeout.setTimeout (/home/owt/management_api/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:198:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:19566) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
getaddrinfo EAI_AGAIN mongodb mongodb:27017
getaddrinfo EAI_AGAIN mongodb mongodb:27017
getaddrinfo EAI_AGAIN mongodb mongodb:27017
getaddrinfo EAI_AGAIN mongodb mongodb:27017
getaddrinfo EAI_AGAIN mongodb mongodb:27017
getaddrinfo EAI_AGAIN mongodb mongodb:27017
getaddrinfo EAI_AGAIN mongodb mongodb:27017
getaddrinfo EAI_AGAIN mongodb mongodb:27017
getaddrinfo EAI_AGAIN mongodb mongodb:27017
getaddrinfo EAI_AGAIN mongodb mongodb:27017

--

Let me know if there is more information I should provide or if I should post this somewhere else.

**Comment by starwarfan** [comment]
It seems that you mongodb url was not correct. Please check that configuration item in portal.toml, conference_agent/agent.toml, managment_api.toml.

**Comment by richard-romano** [comment]
> It seems that you mongodb url was not correct. Please check that configuration item in portal.toml, conference_agent/agent.toml, managment_api.toml.

Thanks for the response. The issue was in the startowt.sh during ./management_api/init.sh --dburl=${mongourl}
it is changing the toml mongourl there.

It changes it from localhost/owtdb to mongodb://localhost/owtdb for some reason.

I can use sed to change it back so its not a big deal now but not sure what if anything would be a proper fix for it.
