### ISSUE TITLE
Getting errors (mac verify failure) in app and portal (V.5.0)

### ISSUE THREAD

**Issue by Chandramouli-P** [open-webrtc-toolkit/owt-server#1098]
Hello,

Please find the environment below:

Intel OWT Server v.5.0
Operating System: Ubuntu 18.04 (64-bit) Server
NodeJS Version: v10.24.1
NPM Version: 6.14.12
Firewall: All ports are completely opened in the firewall and as well as in the server also

After executing "sudo bin/start-all.sh" command, I am getting the below errors:

**app.stdout:**
Build http(s) req error: { Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3000 }
getRooms failed( 503 ): { Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3000 }
_tls_common.js:210
        c.context.loadPKCS12(buf, crypto._toBuf(passphrase));
                  ^

Error: mac verify failure
    at Object.createSecureContext (_tls_common.js:210:19)
    at Server (_tls_wrap.js:903:27)
    at Server (https.js:62:14)
    at Server._init (/home/chandramouli/Release-v5.0/apps/current_app/node_modules/spdy/lib/spdy/server.js:62:10)
    at new Server (/home/chandramouli/Release-v5.0/apps/current_app/node_modules/spdy/lib/spdy/server.js:25:10)
    at Function.create (/home/chandramouli/Release-v5.0/apps/current_app/node_modules/spdy/lib/spdy/server.js:30:12)
    at Object.create [as createServer] (/home/chandramouli/Release-v5.0/apps/current_app/node_modules/spdy/lib/spdy/server.js:286:27)
    at cb (/home/chandramouli/Release-v5.0/apps/current_app/samplertcservice.js:552:10)
    at Gunzip.<anonymous> (/home/chandramouli/Release-v5.0/apps/current_app/cipher.js:51:5)
    at Gunzip.emit (events.js:203:15)

**Portal.stdout:**
2021-10-05 17:05:12.896  - INFO: AmqpClient - Connecting to rabbitMQ server OK, options: [Object: null prototype] { host: 'somedomain.com', port: 5672 }
2021-10-05 17:05:12.907  - INFO: Main - portal initializing as rpc client ok
2021-10-05 17:05:12.915  - INFO: Main - portal join cluster ok, with rpcID: portal-f50a99f180485ae2aa59@somedomain.com
2021-10-05 17:05:12.915  - INFO: ClusterWorker - Join cluster owt-cluster OK.
2021-10-05 17:05:12.921  - INFO: Main - portal initializing as rpc server ok
2021-10-05 17:05:12.925  - INFO: Main - portal-f50a99f180485ae2aa59@somedomain.com as monitor ready
_tls_common.js:210
        c.context.loadPKCS12(buf, crypto._toBuf(passphrase));
                  ^

Error: mac verify failure
    at Object.createSecureContext (_tls_common.js:210:19)
    at Server (_tls_wrap.js:903:27)
    at new Server (https.js:62:14)
    at Object.createServer (https.js:85:10)
    at /home/chandramouli/Release-v5.0/portal/socketIOServer.js:1:5687
    at Gunzip.<anonymous> (/home/chandramouli/Release-v5.0/portal/cipher.js:1:889)
    at Gunzip.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**sip-portal.stdout:**
2021-10-05 17:05:12.151  - INFO: AmqpClient - Connecting to rabbitMQ server OK, options: [Object: null prototype] { host: 'somedomain.com', port: 5672 }
2021-10-05 17:05:12.166  - INFO: SipPortal - sip-portal up!
2021-10-05 17:05:12.217  - INFO: SipPortal - initSipRooms ok
2021-10-05 17:05:12.223  - INFO: SipErizoHelper - Successully schedule sip node  sip-61fe5acd7f7621318bf1@192.168.2.4_0  for  { room: '5e60d0033ca497055f794af5',
  task: '5e60d0033ca497055f794af5' }
2021-10-05 17:05:12.225  - INFO: SipErizoHelper - Successully schedule sip node  sip-61fe5acd7f7621318bf1@192.168.2.4_1  for  { room: '5ed13ca38ab9de2fe262dfb4',
  task: '5ed13ca38ab9de2fe262dfb4' }
2021-10-05 17:05:14.226  - ERROR: SipPortal - Init sip node fail, try to de-allocate it: Timeout to make rpc to sip-61fe5acd7f7621318bf1@192.168.2.4_1.init

Hence, request you to resolve the above issues. Thank you.

Best Regards,
Chandramouli.

**Comment by Chandramouli-P** [comment]
Hello,

I am able to do it now and it is working fine. Thank you.

Best Regards,
Chandramouli.
