### ISSUE TITLE
webrtc-agent crash : munmap_chunk(): invalid pointer

### ISSUE THREAD

**Issue by svener** [open-webrtc-toolkit/owt-server#1182]
Ubuntu 18.04.5 LTS : 32C/32G/500G
owt-server version:   Bump url-parse from 1.5.7 to 1.5.10 in /source/agent/quic (#1177)
node:                         v14.19.0

Multiple users come in and out repeatedly  

```
webrtc-xxxxxx.log
......
2022-03-03 14:53:29,852  - WARN: owt.InternalServer - Mapped StreamID :0340bd72be474477ae7659ba27f36c41-0 0x690a588
2022-03-03 14:53:29,857  - WARN: owt.InternalServer - Mapped StreamID :0340bd72be474477ae7659ba27f36c41-1 0x5b7c388
2022-03-03 14:53:29,869  - DEBUG: owt.InternalClient - onFeedback
2022-03-03 14:53:29,906  - DEBUG: owt.InternalClient - onFeedback
2022-03-03 14:53:29,947  - WARN: WebRtcConnection - id: 277fd18a9a9d4428884f89dca97dff41,  message: addRemoteCandidate on NULL transport
2022-03-03 14:53:29,949  - DEBUG: owt.InternalServer - addSource 277fd18a9a9d4428884f89dca97dff41-0, 0x7235ae8
2022-03-03T14:53:29.950  - ERROR: WrtcConnection - sender error
2022-03-03 14:53:29,950  - DEBUG: owt.InternalServer - addSource 277fd18a9a9d4428884f89dca97dff41-1, 0x8b0dae8
munmap_chunk(): invalid pointer
```

```
gdb node core._root__nvm_versions_node_v14_19_0_bin_node.0.xxxxxx
(gdb) bt
#0  0x00007fd115191e87 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fd1151937f1 in __GI_abort () at abort.c:79
#2  0x00007fd1151dc837 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7fd115309a7b "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007fd1151e38ba in malloc_printerr (str=str@entry=0x7fd11530b690 "munmap_chunk(): invalid pointer") at malloc.c:5342
#4  0x00007fd1151eae9c in munmap_chunk (p=0x7fd0d8038d60) at malloc.c:2846
#5  0x00007fd1151eae9c in __GI___libc_free (mem=0x7fd0d8038d70) at malloc.c:3127
#6  0x00007fd0fe312cad in __gnu_cxx::new_allocator<char>::deallocate(char*, unsigned long) (this=0x7fd0d812e458, __p=<optimized out>) at /usr/include/c++/7/ext/new_allocator.h:125
#7  0x00007fd0fe312cad in std::allocator_traits<std::allocator<char> >::deallocate(std::allocator<char>&, char*, unsigned long) (__a=..., __n=<optimized out>, __p=<optimized out>) at /usr/include/c++/7/bits/alloc_traits.h:462
#8  0x00007fd0fe312cad in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_destroy(unsigned long) (__size=<optimized out>, this=0x7fd0d812e458) at /usr/include/c++/7/bits/basic_string.h:226
#9  0x00007fd0fe312cad in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose() (this=0x7fd0d812e458) at /usr/include/c++/7/bits/basic_string.h:221
#10 0x00007fd0fe312cad in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string() (this=0x7fd0d812e458, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/basic_string.h:647
#11 0x00007fd0fe312cad in erizo::ExtMap::~ExtMap() (this=0x7fd0d812e450, __in_chrg=<optimized out>) at ../erizo/src/erizo/SdpInfo.h:131
#12 0x00007fd0fe312cad in std::_Destroy<erizo::ExtMap>(erizo::ExtMap*) (__pointer=<optimized out>) at /usr/include/c++/7/bits/stl_construct.h:98
#13 0x00007fd0fe312cad in std::_Destroy_aux<false>::__destroy<erizo::ExtMap*>(erizo::ExtMap*, erizo::ExtMap*) (__last=<optimized out>, __first=0x7fd0d812e450) at /usr/include/c++/7/bits/stl_construct.h:108
#14 0x00007fd0fe312cad in std::_Destroy<erizo::ExtMap*>(erizo::ExtMap*, erizo::ExtMap*) (__last=<optimized out>, __first=<optimized out>) at /usr/include/c++/7/bits/stl_construct.h:137
#15 0x00007fd0fe312cad in std::_Destroy<erizo::ExtMap*, erizo::ExtMap>(erizo::ExtMap*, erizo::ExtMap*, std::allocator<erizo::ExtMap>&) (__last=<optimized out>, __first=<optimized out>) at /usr/include/c++/7/bits/stl_construct.h:206
#16 0x00007fd0fe312cad in std::vector<erizo::ExtMap, std::allocator<erizo::ExtMap> >::~vector() (this=0x8f9b6e8, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/stl_vector.h:434
#17 0x00007fd0fe312cad in erizo::SdpInfo::~SdpInfo() (this=0x8f9b580, __in_chrg=<optimized out>) at ../erizo/src/erizo/SdpInfo.cpp:68
#18 0x00000000009dfae7 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() ()
#19 0x00007fd0fe331903 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() (this=0x85a3180, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/shared_ptr_base.h:684
#20 0x00007fd0fe331903 in std::__shared_ptr<erizo::SdpInfo, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() (this=0x85a3178, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/shared_ptr_base.h:1123
#21 0x00007fd0fe331903 in std::shared_ptr<erizo::SdpInfo>::~shared_ptr() (this=0x85a3178, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/shared_ptr.h:93
#22 0x00007fd0fe331903 in erizo::WebRtcConnection::~WebRtcConnection() (this=0x85a2cd0, __in_chrg=<optimized out>) at ../erizo/src/erizo/WebRtcConnection.cpp:66
#23 0x00000000009dfae7 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() ()
#24 0x00007fd0fe326095 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() (this=0x7819048, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/shared_ptr_base.h:684
#25 0x00007fd0fe326095 in std::__shared_ptr<erizo::WebRtcConnection, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() (this=0x7819040, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/shared_ptr_base.h:1123
#26 0x00007fd0fe326095 in std::shared_ptr<erizo::WebRtcConnection>::~shared_ptr() (this=0x7819040, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/shared_ptr.h:93
#27 0x00007fd0fe326095 in erizo::WebRtcConnection::<lambda(std::shared_ptr<erizo::WebRtcConnection>)>::~<lambda> (this=0x7819040, __in_chrg=<optimized out>) at ../erizo/src/erizo/WebRtcConnection.cpp:95
#28 0x00007fd0fe326095 in std::_Function_base::_Base_manager<erizo::WebRtcConnection::close()::<lambda(std::shared_ptr<erizo::WebRtcConnection>)> >::_M_destroy (__victim=...) at /usr/include/c++/7/bits/std_function.h:207
#29 0x00007fd0fe326095 in std::_Function_base::_Base_manager<erizo::WebRtcConnection::close()::<lambda(std::shared_ptr<erizo::WebRtcConnection>)> >::_M_manager(std::_Any_data &, const std::_Any_data &, std::_Manager_operation) (__dest=..., __source=..., __op=<optimized out>) at /usr/include/c++/7/bits/std_function.h:231
#30 0x00007fd0fe32afd6 in std::_Function_base::~_Function_base() (this=0x7162c80, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/std_function.h:276
#31 0x00007fd0fe32afd6 in std::function<void (std::shared_ptr<erizo::WebRtcConnection>)>::~function() (this=0x7162c80, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/std_function.h:389
#32 0x00007fd0fe32afd6 in erizo::WebRtcConnection::<lambda()>::~<lambda> (this=0x7162c70, __in_chrg=<optimized out>) at ../erizo/src/erizo/WebRtcConnection.cpp:619
#33 0x00007fd0fe32afd6 in std::_Function_base::_Base_manager<erizo::WebRtcConnection::asyncTask(std::function<void(std::shared_ptr<erizo::WebRtcConnection>)>)::<lambda()> >::_M_destroy (__victim=...) at /usr/include/c++/7/bits/std_function.h:207
#34 0x00007fd0fe32afd6 in std::_Function_base::_Base_manager<erizo::WebRtcConnection::asyncTask(std::function<void(std::shared_ptr<erizo::WebRtcConnection>)>)::<lambda()> >::_M_manager(std::_Any_data &, const std::_Any_data &, std::_Manager_operation) (__dest=..., __source=..., __op=<optimized out>) at /usr/include/c++/7/bits/std_function.h:231
#35 0x00007fd0fe35bb84 in std::_Function_base::~_Function_base() (this=0x7fd0ea321c40, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/std_function.h:276
#36 0x00007fd0fe35bb84 in std::function<void ()>::~function() (this=0x7fd0ea321c40, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/std_function.h:389
#37 0x00007fd0fe35bb84 in boost::asio::detail::completion_handler<std::function<void ()> >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) (owner=0x4b98230, base=0x5260230) at /usr/include/boost/asio/detail/completion_handler.hpp:59
#38 0x00007fd0fe35c7bb in boost::asio::detail::task_io_service_operation::complete(boost::asio::detail::task_io_service&, boost::system::error_code const&, unsigned long) (bytes_transferred=<optimized out>, ec=..., owner=..., this=<optimized out>) at /usr/include/boost/asio/detail/task_io_service_operation.hpp:38
#39 0x00007fd0fe35c7bb in boost::asio::detail::task_io_service::do_run_one(boost::asio::detail::scoped_lock<boost::asio::detail::posix_mutex>&, boost::asio::detail::task_io_service_thread_info&, boost::system::error_code const&) (ec=..., this_thread=..., lock=..., this=0x4b98230) at /usr/include/boost/asio/detail/impl/task_io_service.ipp:372
#40 0x00007fd0fe35c7bb in boost::asio::detail::task_io_service::run(boost::system::error_code&) (this=0x4b98230, ec=...) at /usr/include/boost/asio/detail/impl/task_io_service.ipp:149
#41 0x00007fd0fe357c72 in boost::asio::io_service::run() (this=0x4abf3f0) at /usr/include/boost/asio/impl/io_service.ipp:59
#42 0x00007fd0fe357c72 in erizo::Worker::<lambda()>::operator() (__closure=0x4bf7db8) at ../erizo/src/erizo/thread/Worker.cpp:50
#43 0x00007fd0fe357c72 in boost::detail::thread_data<erizo::Worker::start(std::shared_ptr<std::promise<void> >)::<lambda()> >::run(void) (this=0x4bf7c00) at /usr/include/boost/thread/detail/thread.hpp:116
#44 0x00007fd10c0c7bcd in  () at /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.65.1
#45 0x00007fd11554b6db in start_thread (arg=0x7fd0ea322700) at pthread_create.c:463
#46 0x00007fd11527461f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by starwarfan** [comment]
Hello, how many users in your scenario?

**Comment by svener** [comment]
1. The browser enters a user to observe
2. Test tool 1 enters 10 users, calls the API and exits normally
3. Test tool 2 enters 10 users, kills the process, and exits abnormally
4. Repeat operations 2 and 3 several times, and webrtc-agent will exit abnormally
