### ISSUE TITLE
node-gyp configure error

### ISSUE THREAD

**Issue by shanweisun** [open-webrtc-toolkit/owt-server#119]
binding.gyp not found (cwd: /opt/nodejs/lib/node_modules/node-gyp) while trying to load binding.gyp
![image](https://user-images.githubusercontent.com/50400477/57369504-4feb7000-71c0-11e9-9b4d-48ed245fb67b.png)

**Comment by starwarfan** [comment]
Hi, what 're the steps to produce this error?

**Comment by kismeter** [comment]
I met similar issue when run ```scripts/build.js -t all --check``` Building add-on - logger

**Comment by xiandeatintel** [comment]
@shanweisun @kismeter We will close this issue since detailed reproduce steps are not provided. and the build.js script runs perfectly well on our side every day. If it is still an issue on your side, please reopen this issue with further detailed description and reproduce steps. thanks.

**Comment by ygavrishov** [comment]
I got the same error. Steps:

- provision a clean Ubuntu 18.04.4 LTS VM
- git clone https://github.com/open-webrtc-toolkit/owt-server.git
- cd owt-server
- scripts/installDepsUnattended.sh
- scripts/build.js -t all --check (got the error node js is not installed)
- sudo apt-get install nodejs
- scripts/build.js -t all --check

Result:
```
/home/broadcastAdmin/owt-server/build/libdeps/build/lib/pkgconfig:/home/broadcastAdmin/owt-server/build/libdeps/build/lib64/pkgconfig:
Following targets will be built:
 video-mixer-sw
 video-transcoder-sw
 video-analyzer-sw
 internal-io
 logger
 media-frame-multicaster
 audio
 webrtc-conn
 webrtc-frame
 avstream
 sip
 video-mixer-msdk
 video-transcoder-msdk
Building addon - video-mixer-sw
/bin/sh: 1: node-gyp: not found
child_process.js:644
    throw err;
    ^

Error: Command failed: node-gyp configure --loglevel=error
    at checkExecSyncError (child_process.js:601:13)
    at execSync (child_process.js:641:13)
    at buildTarget (/home/broadcastAdmin/owt-server/scripts/build.js:132:5)
    at buildList.map (/home/broadcastAdmin/owt-server/scripts/build.js:161:10)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/home/broadcastAdmin/owt-server/scripts/build.js:156:23)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

```

**Comment by arghideutis** [comment]
I have the same error when installing on a fresh 18.04 VM. Can anyone helps? Thanks
