### ISSUE TITLE
conference error

### ISSUE THREAD

**Issue by 516131179** [open-webrtc-toolkit/owt-server#122]
请问：我在做common合流录制   和 stream out  common流时，发现了一个错误， 这个错误导致我的录制和avstreamout  全都断了。  请问原因是什么？  我改如何解决？ 我没有找到必现的办法。

2019-05-09 18:10:15.907  - INFO: ErizoJS - pid: 25198
2019-05-09 18:10:15.910  - INFO: ErizoJS - Connecting to rabbitMQ server...
2019-05-09 18:10:15.923  - INFO: AmqpClient - Connecting to rabbitMQ server OK, hostPort: { port: 5672, host: '172.19.99.192' }
2019-05-09 18:10:16.253  - INFO: ErizoJS - conference-b490235e1a5144e72e3e@172.19.99.106_123 as rpc server ready
2019-05-09 18:10:16.261  - INFO: ErizoJS - conference-b490235e1a5144e72e3e@172.19.99.106_123 as monitor ready
2019-05-09 18:57:09.102  - INFO: AccessController - onFailed, sessionId: 817101023342985200 reason: Ice procedure failed.
2019-05-09 19:00:24.756  - INFO: AccessController - onFailed, sessionId: 214967379394110700 reason: Ice procedure failed.
2019-05-09 19:00:32.894  - INFO: AccessController - onFailed, sessionId: 47526629738205980 reason: Ice procedure failed.
2019-05-09 19:02:37.681  - INFO: AccessController - onFailed, sessionId: 513596918915366400 reason: Ice procedure failed.
2019-05-09 19:02:52.946  - INFO: AccessController - onFailed, sessionId: 716003696789593700 reason: Ice procedure failed.
2019-05-09 19:03:06.752  - INFO: AccessController - onFailed, sessionId: 313260752689476600 reason: Ice procedure failed.
2019-05-09 19:07:28.474  - INFO: AccessController - onFailed, sessionId: 263852884465915600 reason: Ice procedure failed.
2019-05-09 19:07:28.477  - INFO: AccessController - onFailed, sessionId: 463073985260268100 reason: Ice procedure failed.
2019-05-09 19:07:33.283  - INFO: AccessController - onFailed, sessionId: 912684911788369300 reason: Ice procedure failed.
2019-05-09 19:07:33.427  - INFO: AccessController - onFailed, sessionId: 616268868889905700 reason: Ice procedure failed.
2019-05-09 19:07:45.884  - INFO: AccessController - onFailed, sessionId: 56709911362741840 reason: Ice procedure failed.
2019-05-09 19:07:45.891  - INFO: AccessController - onFailed, sessionId: 154503511660518900 reason: Ice procedure failed.
2019-05-09 19:14:14.649  - INFO: AccessController - onFailed, sessionId: 375296101689233800 reason: Audio/Video not enabled
2019-05-09 19:14:14.709  - INFO: ErizoJS - Reason: Session does NOT exist
2019-05-09 19:29:09.462  - INFO: AccessController - onFailed, sessionId: 649192817481452000 reason: Ice procedure failed.
2019-05-09 19:29:27.559  - INFO: AccessController - onFailed, sessionId: 499847782140638850 reason: Ice procedure failed.
2019-05-09 19:29:47.719  - INFO: AccessController - onFailed, sessionId: 840383076455240400 reason: Ice procedure failed.
2019-05-09 19:29:49.268  - INFO: AccessController - onFailed, sessionId: 172070783736275170 reason: Ice procedure failed.
2019-05-09 19:35:18.953  - INFO: AccessController - onFailed, sessionId: 421332979021594300 reason: Ice procedure failed.
2019-05-09 19:39:43.008  - INFO: AccessController - onFailed, sessionId: 464476480200873400 reason: Ice procedure failed.
2019-05-09 19:39:49.354  - INFO: AccessController - onFailed, sessionId: 796787743095899000 reason: Ice procedure failed.
2019-05-09 19:45:36.533  - INFO: AccessController - onFailed, sessionId: 204181635681597980 reason: Ice procedure failed.
2019-05-09 19:45:40.292  - INFO: AccessController - onFailed, sessionId: 310576647233127500 reason: Ice procedure failed.
2019-05-09 19:46:18.329  - INFO: AccessController - onFailed, sessionId: 810466519068879100 reason: Ice procedure failed.
2019-05-09 19:46:19.401  - INFO: AccessController - onFailed, sessionId: 457618319457187460 reason: Ice procedure failed.
2019-05-09 19:50:28.761  - INFO: AccessController - onFailed, sessionId: 874991772164875000 reason: Ice procedure failed.
2019-05-09 19:50:47.429  - INFO: AccessController - onFailed, sessionId: 863868558306994700 reason: Ice procedure failed.
2019-05-09 19:50:57.374  - INFO: AccessController - onFailed, sessionId: 560635516828806660 reason: Ice procedure failed.
2019-05-09 19:51:01.546  - INFO: AccessController - onFailed, sessionId: 763450353216536400 reason: Ice procedure failed.
2019-05-09 19:51:13.625  - INFO: AccessController - onFailed, sessionId: 192159266824961440 reason: Ice procedure failed.
2019-05-09 19:51:27.174  - INFO: AccessController - onFailed, sessionId: 567156762552735600 reason: Ice procedure failed.
2019-05-09 19:53:10.528  - INFO: AccessController - onFailed, sessionId: 313747738914956540 reason: Ice procedure failed.
2019-05-09 19:53:11.401  - INFO: AccessController - onFailed, sessionId: 429480765803332000 reason: Ice procedure failed.
2019-05-09 19:54:24.800  - INFO: AccessController - onFailed, sessionId: 899452961556146200 reason: Ice procedure failed.
2019-05-09 19:54:24.845  - INFO: AccessController - onFailed, sessionId: 571895253159079500 reason: Ice procedure failed.
2019-05-09 19:55:36.591  - INFO: AccessController - onFailed, sessionId: 904173031807513900 reason: Ice procedure failed.
2019-05-09 19:55:40.391  - INFO: AccessController - onFailed, sessionId: 361415986044764350 reason: Ice procedure failed.
2019-05-09 19:55:40.439  - INFO: AccessController - onFailed, sessionId: 74009445089235000 reason: Ice procedure failed.
2019-05-09 19:55:48.515  - INFO: AccessController - onFailed, sessionId: 262354778074207040 reason: Ice procedure failed.
2019-05-09 19:56:01.202  - INFO: AccessController - onFailed, sessionId: 24429111943926828 reason: Ice procedure failed.
2019-05-09 19:59:01.407  - INFO: AccessController - onFailed, sessionId: 338968248467986100 reason: Ice procedure failed.
2019-05-09 19:59:01.415  - INFO: AccessController - onFailed, sessionId: 366521391193370240 reason: Ice procedure failed.
2019-05-09 20:03:39.564  - INFO: AccessController - onFailed, sessionId: 441675794771840600 reason: Ice procedure failed.
2019-05-09 20:07:21.136  - INFO: AccessController - onFailed, sessionId: 159687649460667400 reason: Ice procedure failed.
2019-05-09 20:07:21.334  - INFO: AccessController - onFailed, sessionId: 353760667193920640 reason: Ice procedure failed.
2019-05-09 20:08:18.949  - INFO: AccessController - onFailed, sessionId: 307652679454497800 reason: Ice procedure failed.
2019-05-09 20:08:28.278  - INFO: AccessController - onFailed, sessionId: 163692181848575040 reason: Ice procedure failed.
2019-05-09 20:14:57.258  - INFO: AccessController - onFailed, sessionId: 967525552841901000 reason: Ice procedure failed.
2019-05-09 20:15:30.717  - INFO: AccessController - onFailed, sessionId: 663634617257125200 reason: Ice procedure failed.
2019-05-09 20:15:31.773  - INFO: AccessController - onFailed, sessionId: 170878463672961440 reason: Ice procedure failed.
2019-05-09 20:20:41.221  - INFO: AccessController - onFailed, sessionId: 530109445859163100 reason: Ice procedure failed.
2019-05-09 20:23:47.477  - INFO: AccessController - onFailed, sessionId: 703833212190790400 reason: Ice procedure failed.
2019-05-09 20:24:13.522  - INFO: AccessController - onFailed, sessionId: 658038670454330600 reason: Ice procedure failed.
2019-05-09 20:25:20.075  - INFO: AccessController - onFailed, sessionId: 148747911546617920 reason: Ice procedure failed.
2019-05-09 20:29:55.328  - INFO: AccessController - onFailed, sessionId: 817122533853637200 reason: Ice procedure failed.
2019-05-09 20:30:00.193  - INFO: AccessController - onFailed, sessionId: 833908848761391100 reason: Ice procedure failed.
2019-05-09 20:34:21.665  - INFO: AccessController - onFailed, sessionId: 890179194714945300 reason: Ice procedure failed.
2019-05-09 20:34:21.711  - INFO: AccessController - onFailed, sessionId: 594819073159767800 reason: Ice procedure failed.
2019-05-09 21:00:33.205  - INFO: AccessController - onFailed, sessionId: 722580959832934900 reason: Ice procedure failed.
2019-05-09 21:00:59.773  - INFO: AccessController - onFailed, sessionId: 384484073046253760 reason: Ice procedure failed.
2019-05-09 21:01:49.196  - INFO: AccessController - onFailed, sessionId: 12584509804759670 reason: Ice procedure failed.
2019-05-09 21:02:06.439  - INFO: AccessController - onFailed, sessionId: 363868304468609700 reason: Ice procedure failed.
2019-05-09 21:09:41.889  - ERROR: RoomController - subscribe failed, reason: Subscription does not exist:990411044389816700
2019-05-09 21:09:41.889  - INFO: Conference - roomController.subscribe failed, reason: Subscription does not exist:990411044389816700
2019-05-09 21:09:41.889  - INFO: Conference - Exception: roomController.subscribe failed, reason: Subscription does not exist:990411044389816700
2019-05-09 21:09:41.889  - INFO: Conference - Exception: Session does NOT exist
2019-05-09 21:09:41.895  - ERROR: AccessController - Session does NOT exist
2019-05-09 21:09:41.895  - INFO: ErizoJS - Reason: Session does NOT exist
2019-05-09 21:09:41.920  - ERROR: RoomController - spreadStream failed, stream_id: 204134646954899900 reason: Stream does not exist!
2019-05-09 21:09:41.920  - ERROR: RoomController - subscribe failed, reason: Stream does not exist!
2019-05-09 21:09:41.921  - INFO: Conference - roomController.subscribe failed, reason: Stream does not exist!
2019-05-09 21:09:41.921  - INFO: Conference - Exception: roomController.subscribe failed, reason: Stream does not exist!
2019-05-09 21:09:41.921  - INFO: Conference - Exception: Session does NOT exist
2019-05-09 21:09:41.988  - ERROR: RoomController - subscribe failed, reason: Uncomplished subscription.
2019-05-09 21:09:41.989  - INFO: Conference - roomController.subscribe failed, reason: Uncomplished subscription.
2019-05-09 21:09:41.989  - INFO: Conference - Exception: roomController.subscribe failed, reason: Uncomplished subscription.
2019-05-09 21:09:41.989  - INFO: Conference - Exception: Session does NOT exist
/var/www/dream/atlas-agent/Release-v4.1/conference_agent/roomController.js:1
(function (exports, require, module, __filename, __dirname) { "use strict";var _typeof="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(e){return typeof e}:function(e){return e&&"function"==typeof Symbol&&e.constructor===Symbol&&e!==Symbol.prototype?"symbol":typeof e},assert=require("assert"),logger=require("./logger").logger,makeRPC=require("./makeRPC").makeRPC,log=logger.getLogger("RoomController");function isResolutionEqual(e,i){return e.width&&i.width&&e.height&&i.height&&e.width===i.width&&e.height===i.height}module.exports.create=function(e,i,o){var r,t={},u=e.cluster,d=e.rpcReq,k=e.rpcClient,s=e.config,P=e.room,g=e.selfRpcId,R=s.transcoding&&!!s.transcoding.audio,_=s.transcoding&&!!s.transcoding.video,p=s.internalConnProtocol,C={},I={},S={},c=((r={}).video={encode:s.mediaOut.video.format.map(H),decode:s.mediaIn.video.map(H)},s.mediaOut.video.format,s.views.forEach(function(e){e.video.format&&r.video.encod

TypeError: Cannot read property 'waiting' of undefined
    at /var/www/dream/atlas-agent/Release-v4.1/conference_agent/roomController.js:1:4544
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by xiandeatintel** [comment]
Seems like network issue which caused "ICE procedure failure" according to the log.
