### ISSUE TITLE
'webrtc/system_wrappers/include/clock.h' file not found

### ISSUE THREAD

**Issue by qianjinyuan** [open-webrtc-toolkit/owt-server#1281]
I encountered the following problem, how should I do?

../../SoftVideoCompositor.h:15:10: fatal error: 'webrtc/system_wrappers/include/clock.h' file not
      found
#include <webrtc/system_wrappers/include/clock.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/videoMixer-sw/../SoftVideoCompositor.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/vladimir.minkin/.nvm/versions/node/v10.22.0/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/vladimir.minkin/.nvm/versions/node/v10.22.0/bin/node" "/Users/vladimir.minkin/.nvm/versions/node/v10.22.0/bin/node-gyp" "build" "-j" "8" "--loglevel=error"
gyp ERR! cwd /Users/vladimir.minkin/Documents/Projects/Personal/OWT/owt-server/source/agent/video/videoMixer/videoMixer_sw
gyp ERR! node -v v10.22.0
gyp ERR! node-gyp -v v7.1.0
gyp ERR! not ok 
child_process.js:669
    throw err;
    ^

Error: Command failed: node-gyp build -j 8 --loglevel=error
    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at buildTarget (/Users/vladimir.minkin/Documents/Projects/Personal/OWT/owt-server/scripts/build.js:133:5)
    at buildList.map (/Users/vladimir.minkin/Documents/Projects/Personal/OWT/owt-server/scripts/build.js:161:10)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/Users/vladimir.minkin/Documents/Projects/Personal/OWT/owt-server/scripts/build.js:156:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

**Comment by tenchong** [comment]
同问

**Comment by starwarfan** [comment]
The webrtc dependency is not installed succesfully. Run `scripts/installDeps.sh --only webrtc` to install.
