### ISSUE TITLE
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: cannot find -lwebrtc

### ISSUE THREAD

**Issue by tenchong** [open-webrtc-toolkit/owt-server#1310]
make: Entering directory `/usr/owt-server-master/source/agent/webrtc/rtcFrame/build'
  SOLINK(target) Release/obj.target/rtcadapter.so
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: cannot find -lwebrtc
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/rtcadapter.so] Error 1
make: Leaving directory `/usr/owt-server-master/source/agent/webrtc/rtcFrame/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v14.21.3/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Linux 3.10.0-1160.71.1.el7.x86_64
gyp ERR! command "/root/.nvm/versions/node/v14.21.3/bin/node" "/root/.nvm/versions/node/v14.21.3/bin/node-gyp" "build" "-j" "1" "--loglevel=error"
gyp ERR! cwd /usr/owt-server-master/source/agent/webrtc/rtcFrame
gyp ERR! node -v v14.21.3
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
child_process.js:866
    throw err;
    ^

Error: Command failed: node-gyp build -j 1 --loglevel=error
    at checkExecSyncError (child_process.js:790:11)
    at execSync (child_process.js:863:15)
    at buildTarget (/usr/owt-server-master/scripts/build.js:147:5)
    at /usr/owt-server-master/scripts/build.js:175:10
    at Array.map (<anonymous>)
    at Object.<anonymous> (/usr/owt-server-master/scripts/build.js:170:23)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 22261,
  stdout: null,
  stderr: null
}

**Comment by tenchong** [comment]
请教一下大神这个是什么原因呢？
