### ISSUE TITLE
When I execute scripts/installDepsUnattended.sh on ubuntu18.04 system, I get an error. How to solve it?

### ISSUE THREAD

**Issue by sawsam** [open-webrtc-toolkit/owt-server#1374]
Syncing projects: 100% (42/42), done.                                           
Running hooks:  68% (15/22) clang_format_linux
________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s src/buildtools/linux64/clang-format.sha1' in '/home/xsq/owt-server/owt-server/third_party/webrtc-m88'
NOTICE: You have PROXY values set in your environment, but gsutil in depot_tools does not (yet) obey them.
Also, --no_auth prevents the normal BOTO_CONFIG environment variable from being used.
To use a proxy in this situation, please supply those settings in a .boto file pointed to by the NO_AUTH_BOTO_CONFIG environment variable.
Running hooks:  86% (19/22) test_fonts        
________ running 'download_from_google_storage --no_resume --extract --no_auth --bucket chromium-fonts -s src/third_party/test_fonts/test_fonts.tar.gz.sha1' in '/home/xsq/owt-server/owt-server/third_party/webrtc-m88'
NOTICE: You have PROXY values set in your environment, but gsutil in depot_tools does not (yet) obey them.
Also, --no_auth prevents the normal BOTO_CONFIG environment variable from being used.
To use a proxy in this situation, please supply those settings in a .boto file pointed to by the NO_AUTH_BOTO_CONFIG environment variable.
Running hooks:  90% (20/22) msan_chained_origins
________ running 'python src/third_party/depot_tools/download_from_google_storage.py --no_resume --no_auth --bucket chromium-instrumented-libraries -s src/third_party/instrumented_libraries/binaries/msan-chained-origins-trusty.tgz.sha1' in '/home/xsq/owt-server/owt-server/third_party/webrtc-m88'
NOTICE: You have PROXY values set in your environment, but gsutilin depot_tools does not (yet) obey them.
Also, --no_auth prevents the normal BOTO_CONFIG environmentvariable from being used.
To use a proxy in this situation, please supply those settingsin a .boto file pointed to by the NO_AUTH_BOTO_CONFIG environmentvariable.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "src/third_party/depot_tools/download_from_google_storage.py", line 262, in _downloader_worker_thread
    (code, _, err) = gsutil.check_call('ls', file_url)
  File "src/third_party/depot_tools/download_from_google_storage.py", line 114, in check_call
    env=self.get_sub_env())
  File "/home/xsq/owt-server/owt-server/third_party/webrtc-m88/src/third_party/depot_tools/subprocess2.py", line 193, in communicate
    proc = Popen(args, **kwargs)
  File "/home/xsq/owt-server/owt-server/third_party/webrtc-m88/src/third_party/depot_tools/subprocess2.py", line 174, in __init__
    % (str(e), kwargs.get('cwd'), args[0]))
OSError: Execution failed with error: [Errno 2] No such file or directory.
Check that None or vpython exist and have execution permission.

Running hooks:  95% (21/22) msan_no_origins     
________ running 'python src/third_party/depot_tools/download_from_google_storage.py --no_resume --no_auth --bucket chromium-instrumented-libraries -s src/third_party/instrumented_libraries/binaries/msan-no-origins-trusty.tgz.sha1' in '/home/xsq/owt-server/owt-server/third_party/webrtc-m88'
NOTICE: You have PROXY values set in your environment, but gsutilin depot_tools does not (yet) obey them.
Also, --no_auth prevents the normal BOTO_CONFIG environmentvariable from being used.
To use a proxy in this situation, please supply those settingsin a .boto file pointed to by the NO_AUTH_BOTO_CONFIG environmentvariable.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "src/third_party/depot_tools/download_from_google_storage.py", line 262, in _downloader_worker_thread
    (code, _, err) = gsutil.check_call('ls', file_url)
  File "src/third_party/depot_tools/download_from_google_storage.py", line 114, in check_call
    env=self.get_sub_env())
  File "/home/xsq/owt-server/owt-server/third_party/webrtc-m88/src/third_party/depot_tools/subprocess2.py", line 193, in communicate
    proc = Popen(args, **kwargs)
  File "/home/xsq/owt-server/owt-server/third_party/webrtc-m88/src/third_party/depot_tools/subprocess2.py", line 174, in __init__
    % (str(e), kwargs.get('cwd'), args[0]))
OSError: Execution failed with error: [Errno 2] No such file or directory.
Check that None or vpython exist and have execution permission.

Running hooks: 100% (22/22)                
________ running 'download_from_google_storage --directory --recursive --num_threads=10 --no_auth --quiet --bucket chromium-webrtc-resources src/resources' in '/home/xsq/owt-server/owt-server/third_party/webrtc-m88'
NOTICE: You have PROXY values set in your environment, but gsutil in depot_tools does not (yet) obey them.
Also, --no_auth prevents the normal BOTO_CONFIG environment variable from being used.
To use a proxy in this situation, please supply those settings in a .boto file pointed to by the NO_AUTH_BOTO_CONFIG environment variable.
Hook 'download_from_google_storage --directory --recursive --num_threads=10 --no_auth --quiet --bucket chromium-webrtc-resources src/resources' took 19.47 secs
Running hooks: 100% (22/22), done.
Traceback (most recent call last):
  File "/home/xsq/owt-server/owt-server/third_party/webrtc-m88/tools-owt/depot_tools/gn.py", line 14, in <module>
    import gclient_paths
  File "/home/xsq/owt-server/owt-server/third_party/webrtc-m88/tools-owt/depot_tools/gclient_paths.py", line 24, in <module>
    def FindGclientRoot(from_dir, filename='.gclient'):
  File "/usr/lib/python3.6/functools.py", line 477, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None

**Comment by littebird** [comment]
hello! I have the same problem , how to solve it?

**Comment by htliu6** [comment]
Hello! Did anybody solve this problem? @sawsam @littebird
