### ISSUE TITLE
call bin/init-all.sh will be not restart mongod server if mongod server was bad

### ISSUE THREAD

**Issue by zhangyihui1** [open-webrtc-toolkit/owt-server#215]
os_version : centos7
1: systemctl stop mongod
2: ./bin/init-all.sh

log:
/home/webrtc/workspace/server/source/dist/management_api/node_modules/mongodb/lib/mongo_client.js:421
          throw err
          ^
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/home/webrtc/workspace/server/source/dist/management_api/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/home/webrtc/workspace/server/source/dist/management_api/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/home/webrtc/workspace/server/source/dist/management_api/node_modules/mongodb-core/lib/connection/connection.js:189:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)

**Comment by zhouhuirun2015** [comment]
sometine mongod cannot start in init-all, you should start mongod manully before init-all

**Comment by starwarfan** [comment]
#254
