### ISSUE TITLE
error building webrtc in ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by jorge88cs** [open-webrtc-toolkit/owt-server#338]
Hi
After install develop dependency, I am trying on Build native components by doing:
`scripts / build.js -t all --check`.
This is the terminal output:

/media/user/owt_github/owt-server-4.2.1/build/libdeps/build/lib/pkgconfig:/media/user/owt_github/owt-server-4.2.1/build/libdeps/build/lib64/pkgconfig:
Following targets will be built:
 video-mixer-sw 
 video-transcoder-sw 
 video-analyzer-sw 
 internal-io 
 logger 
 media-frame-multicaster 
 audio 
 webrtc 
 avstream 
 sip 
 video-mixer-msdk 
 video-transcoder-msdk 
Building addon - video-mixer-sw
make: se entra en el directorio '/media/user/owt_github/owt-server-4.2.1/source/agent/video/videoMixer/videoMixer_sw/build'
make: No se hace nada para 'all'.
make: se sale del directorio '/media/user/owt_github/owt-server-4.2.1/source/agent/video/videoMixer/videoMixer_sw/build'
Finish addon - video-mixer-sw
Building addon - video-transcoder-sw
make: se entra en el directorio '/media/user/owt_github/owt-server-4.2.1/source/agent/video/videoTranscoder/videoTranscoder_sw/build'
make: No se hace nada para 'all'.
make: se sale del directorio '/media/user/owt_github/owt-server-4.2.1/source/agent/video/videoTranscoder/videoTranscoder_sw/build'
Finish addon - video-transcoder-sw
Building addon - video-analyzer-sw
make: se entra en el directorio '/media/user/owt_github/owt-server-4.2.1/source/agent/video/videoTranscoder/videoAnalyzer_sw/build'
make: No se hace nada para 'all'.
make: se sale del directorio '/media/user/owt_github/owt-server-4.2.1/source/agent/video/videoTranscoder/videoAnalyzer_sw/build'
Finish addon - video-analyzer-sw
Building addon - internal-io
make: se entra en el directorio '/media/user/owt_github/owt-server-4.2.1/source/agent/addons/internalIO/build'
make: No se hace nada para 'all'.
make: se sale del directorio '/media/user/owt_github/owt-server-4.2.1/source/agent/addons/internalIO/build'
Finish addon - internal-io
Building addon - logger
make: se entra en el directorio '/media/user/owt_github/owt-server-4.2.1/source/agent/addons/logger/build'
make: No se hace nada para 'all'.
make: se sale del directorio '/media/user/owt_github/owt-server-4.2.1/source/agent/addons/logger/build'
Finish addon - logger
Building addon - media-frame-multicaster
make: se entra en el directorio '/media/user/owt_github/owt-server-4.2.1/source/agent/addons/mediaFrameMulticaster/build'
make: No se hace nada para 'all'.
make: se sale del directorio '/media/user/owt_github/owt-server-4.2.1/source/agent/addons/mediaFrameMulticaster/build'
Finish addon - media-frame-multicaster
Building addon - audio
make: se entra en el directorio '/media/user/owt_github/owt-server-4.2.1/source/agent/audio/audioMixer/build'
make: No se hace nada para 'all'.
make: se sale del directorio '/media/user/owt_github/owt-server-4.2.1/source/agent/audio/audioMixer/build'
Finish addon - audio
Building addon - webrtc
make: se entra en el directorio '/media/user/owt_github/owt-server-4.2.1/source/agent/webrtc/webrtcLib/build'
  CXX(target) Release/obj.target/webrtc/WebRtcConnection.o
  CXX(target) Release/obj.target/webrtc/erizo/src/erizo/DtlsTransport.o
  CXX(target) Release/obj.target/webrtc/erizo/src/erizo/thread/IOWorker.o
  CXX(target) Release/obj.target/webrtc/erizo/src/erizo/thread/Scheduler.o
  CXX(target) Release/obj.target/webrtc/erizo/src/erizo/dtls/DtlsClient.o
  CXX(target) Release/obj.target/webrtc/erizo/src/erizo/dtls/DtlsSocket.o
  CXX(target) Release/obj.target/webrtc/erizo/src/erizo/thread/ThreadPool.o
  CXX(target) Release/obj.target/webrtc/erizo/src/erizo/thread/Worker.o
../erizo/src/erizo/thread/IOWorker.cpp:4:10: fatal error: r_errors.h: No existe el archivo o el directorio
 #include <r_errors.h>
          ^~~~~~~~~~~~
compilation terminated.
webrtc.target.mk:242: recipe for target 'Release/obj.target/webrtc/erizo/src/erizo/thread/IOWorker.o' failed
make: *** [Release/obj.target/webrtc/erizo/src/erizo/thread/IOWorker.o] Error 1
make: *** Se espera a que terminen otras tareas....
In file included from ../erizo/src/erizo/DtlsTransport.cpp:14:0:
../erizo/src/erizo/./NicerConnection.h:10:10: fatal error: r_types.h: No existe el archivo o el directorio
 #include <r_types.h>
          ^~~~~~~~~~~
compilation terminated.
webrtc.target.mk:242: recipe for target 'Release/obj.target/webrtc/erizo/src/erizo/DtlsTransport.o' failed
make: *** [Release/obj.target/webrtc/erizo/src/erizo/DtlsTransport.o] Error 1
../WebRtcConnection.cc: In member function ‘virtual void StatCallWorker::HandleOKCallback()’:
../WebRtcConnection.cc:42:25: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
   callback->Call(1, argv);
                         ^
In file included from ../WebRtcConnection.h:4:0,
                 from ../WebRtcConnection.cc:5:
../../../../../node_modules/nan/nan.h:1655:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../WebRtcConnection.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE WebRtcConnection::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../WebRtcConnection.cc:361:17: error: ‘class erizo::IceConfig’ has no member named ‘ip_addresses’
       iceConfig.ip_addresses = ipAddresses;
                 ^~~~~~~~~~~~
../WebRtcConnection.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE WebRtcConnection::removeRemoteCandidate(Nan::NAN_METHOD_ARGS_TYPE)’:
../WebRtcConnection.cc:543:16: error: ‘using element_type = class erizo::WebRtcConnection {aka class erizo::WebRtcConnection}’ has no member named ‘removeRemoteCandidate’; did you mean ‘addRemoteCandidate’?
   bool r = me->removeRemoteCandidate(mid, sdpMLine, sdp);
                ^~~~~~~~~~~~~~~~~~~~~
                addRemoteCandidate
../WebRtcConnection.cc: In static member function ‘static void WebRtcConnection::eventsCallback(uv_async_t*)’:
../WebRtcConnection.cc:707:102: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
     Nan::MakeCallback(Nan::GetCurrentContext()->Global(), obj->eventCallback_->GetFunction(), 2, args);
                                                                                                      ^
In file included from ../WebRtcConnection.h:4:0,
                 from ../WebRtcConnection.cc:5:
../../../../../node_modules/nan/nan.h:958:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
../WebRtcConnection.cc: In static member function ‘static void WebRtcConnection::statsCallback(uv_async_t*)’:
../WebRtcConnection.cc:722:104: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
       Nan::MakeCallback(Nan::GetCurrentContext()->Global(), obj->statsCallback_->GetFunction(), 1, args);
                                                                                                        ^
In file included from ../WebRtcConnection.h:4:0,
                 from ../WebRtcConnection.cc:5:
../../../../../node_modules/nan/nan.h:958:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
webrtc.target.mk:236: recipe for target 'Release/obj.target/webrtc/WebRtcConnection.o' failed
make: *** [Release/obj.target/webrtc/WebRtcConnection.o] Error 1
make: se sale del directorio '/media/user/owt_github/owt-server-4.2.1/source/agent/webrtc/webrtcLib/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-33-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "build" "-j" "8" "--loglevel=error"
gyp ERR! cwd /media/user/owt_github/owt-server-4.2.1/source/agent/webrtc/webrtcLib
gyp ERR! node -v v8.15.0
gyp ERR! node-gyp -v v6.0.0
gyp ERR! not ok 
child_process.js:650
    throw err;
    ^

Error: Command failed: node-gyp build -j 8 --loglevel=error
    at checkExecSyncError (child_process.js:607:13)
    at execSync (child_process.js:647:13)
    at buildTarget (/media/user/owt_github/owt-server-4.2.1/scripts/build.js:129:5)
    at buildList.map (/media/user/owt_github/owt-server-4.2.1/scripts/build.js:153:10)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/media/user/owt_github/owt-server-4.2.1/scripts/build.js:152:23)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)

Did i miss some step or is there any dependency missing?
Thank you.

**Comment by jorge88cs** [comment]
Solution found: https://github.com/open-webrtc-toolkit/owt-server/issues/16
licode dependency missing because git user name and email was not set.
