### ISSUE TITLE
TypeError: write() argument must be str, not bytes while trying to load binding.gyp

### ISSUE THREAD

**Issue by hxl-dy** [open-webrtc-toolkit/owt-server#362]
```sh
docker run --rm -v $PWD:/owt-server fenghao630/owt-server bash -c "scripts/build.js -t all --check"
# or
cd docker && docker build --tag=owt-server .
docker run --rm -v $PWD:/owt-server owt-server bash -c "scripts/build.js -t all --check"
```

```
/owt-server/build/libdeps/build/lib/pkgconfig:/owt-server/build/libdeps/build/lib64/pkgconfig:
Following targets will be built:
 video-mixer-sw 
 video-transcoder-sw 
 video-analyzer-sw 
 internal-io 
 logger 
 media-frame-multicaster 
 audio 
 webrtc 
 avstream 
 sip 
 video-mixer-msdk 
 video-transcoder-msdk 
Building addon - video-mixer-sw
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    options.duplicate_basename_check)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 139, in Load
    params['parallel'], params['root_targets'])
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2779, in Load
    variables, includes, depth, check, True)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 417, in LoadTargetBuildFile
    build_file_data, PHASE_EARLY, variables, build_file_path)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1296, in ProcessVariablesAndConditionsInDict
    build_file)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1311, in ProcessVariablesAndConditionsInList
    ProcessVariablesAndConditionsInDict(item, phase, variables, build_file)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1296, in ProcessVariablesAndConditionsInDict
    build_file)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1315, in ProcessVariablesAndConditionsInList
    expanded = ExpandVariables(item, phase, variables, build_file)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 914, in ExpandVariables
    sys.stderr.write(p_stderr)
TypeError: write() argument must be str, not bytes while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-52-generic
gyp ERR! command "/usr/bin/node" "/usr/local/bin/node-gyp" "configure" "--loglevel=error"
gyp ERR! cwd /owt-server/source/agent/video/videoMixer/videoMixer_sw
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v6.0.0
gyp ERR! not ok 
child_process.js:644
    throw err;
    ^

Error: Command failed: node-gyp configure --loglevel=error
    at checkExecSyncError (child_process.js:601:13)
    at execSync (child_process.js:641:13)
    at buildTarget (/owt-server/scripts/build.js:131:5)
    at buildList.map (/owt-server/scripts/build.js:160:10)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/owt-server/scripts/build.js:155:23)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

```

**Comment by hxl-dy** [comment]
docker run --rm ~~-v $PWD:/owt-server~~ fenghao630/owt-server bash -c "scripts/build.js -t all --check"
