### ISSUE TITLE
video-agent crash!

### ISSUE THREAD

**Issue by linewei** [open-webrtc-toolkit/owt-server#370]
I compiled successed in ubunto 18.04, but video-agent crash fastly.

---------------
2019-11-08 17:32:22.294  - INFO: NodeManager - Node video-522c24c08e5704180c38@172.19.62.236_2 is closed on unexpected code: 254
2019-11-08 17:32:22.302  - INFO: NodeManager - Node video-522c24c08e5704180c38@172.19.62.236_3 is closed on unexpected code: 254
2019-11-08 17:32:22.484  - INFO: NodeManager - Node video-522c24c08e5704180c38@172.19.62.236_4 is closed on unexpected code: 254

2019-11-08 17:35:01.606  - ERROR: VideoNode - Error: libavutil.so.56: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/bokecc/owt-server/dist/video_agent/video/index.js:33:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)

# strings /etc/ld.so.cache |grep libavutil
libavutil.so.55
/usr/lib/x86_64-linux-gnu/libavutil.so.55

**Comment by daijh** [comment]
The video node links with local FFmpeg libs in "video_agent/lib/", instead of system FFmpeg libs.
FFmpeg libs are not part of release package, please install it by " ./bin/init-all.sh --deps
", and make sure all FFmpeg *so in "video_agent/lib/"

**Comment by starwarfan** [comment]
Or you can pack with options '-wf' to include those libs in dist.

**Comment by linewei** [comment]
Hi, starwarfan
Thank you so much!  options '-wf' works for me finally.

but i got a new error when i try to open example app in browser,  local camera opened , the second  candidate try open the same url  , and then error occurs . Can you help me ?  Thanks a lot.

Frankly . OWT is much hard to use. Something not appeared in document. Something changed in new release. I hope we can do better let more people use it.   
-------------

 

(process:2926): libnice-CRITICAL **: 11:13:20.013: file address.c: line 166 (nice_address_set_port): should not be reached

(process:2926): libnice-CRITICAL **: 11:13:20.015: file address.c: line 166 (nice_address_set_port): should not be reached
2019-11-15 11:13:30,050  - WARN: LibNiceConnection - id: 142894756616237300,  message: failed and not received all candidates, newComponentState:4
2019-11-15 11:13:49,566  - WARN: LibNiceConnection - id: 281643446244014720,  message: failed and not received all candidates, newComponentState:4
2019-11-15 11:13:49,607  - WARN: LibNiceConnection - id: 429463359442279400,  message: failed and not received all candidates, newComponentState:4
2019-11-15 11:14:01,426  - WARN: LibNiceConnection - id: 859967620349554000,  message: failed and not received all candidates, newComponentState:4
2019-11-15 11:14:02,236  - WARN: LibNiceConnection - id: 715218120898297100,  message: failed and not received all candidates, newComponentState:4

**Comment by starwarfan** [comment]
@linewei
Hi, which browser did you use? Any errors in web console?
From the error above, your ICE candidates' addresses may not be parsed correctly.

**Comment by linewei** [comment]
@starwarfan  Thank you for reply !
I'm using chrome V78 in mac system. now this problem is resolved.
It's my fault,   when i changed replaced_ip_address in  webrtc_agent/agent.toml. it goes OK.
