### ISSUE TITLE
scripts/build.js -t all --check Error

### ISSUE THREAD

**Issue by azzahrah** [open-webrtc-toolkit/owt-server#378]
[root@localhost owt-server]# scripts/build.js -t all --check.
/home/intel/owt-server/build/libdeps/build/lib/pkgconfig:/home/intel/owt-server/build/libdeps/build/lib64/pkgconfig:
Following targets will be built:
 video-mixer-sw
 video-transcoder-sw
 video-analyzer-sw
 internal-io
 logger
 media-frame-multicaster
 audio
 webrtc
 avstream
 sip
 video-mixer-msdk
 video-transcoder-msdk
Building addon - video-mixer-sw
make: Entering directory `/home/intel/owt-server/source/agent/video/videoMixer/videoMixer_sw/build'
  CXX(target) Release/obj.target/videoMixer-sw/../VideoMixer.o
  CXX(target) Release/obj.target/videoMixer-sw/../../../../core/owt_base/SVTHEVCEncoder.o
In file included from ../../../../../core/owt_base/SVTHEVCEncoder.h:19:0,
                 from ../../../../../core/owt_base/SVTHEVCEncoder.cpp:5:
/usr/local/include/svt-hevc/EbApi.h:12:26: fatal error: EbApiVersion.h: No such file or directory
 #include <EbApiVersion.h>
                          ^
compilation terminated.
In file included from /home/intel/owt-server/source/core/owt_base/SVTHEVCEncoder.h:19:0,
                 from ../../VideoFrameMixerImpl.h:29,
                 from ../../VideoMixer.cpp:9:
/usr/local/include/svt-hevc/EbApi.h:12:26: fatal error: EbApiVersion.h: No such file or directory
 #include <EbApiVersion.h>
                          ^
compilation terminated.
make: *** [Release/obj.target/videoMixer-sw/../../../../core/owt_base/SVTHEVCEncoder.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Release/obj.target/videoMixer-sw/../VideoMixer.o] Error 1
make: Leaving directory `/home/intel/owt-server/source/agent/video/videoMixer/videoMixer_sw/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 3.10.0-957.5.1.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "build" "-j" "32" "--loglevel=error"
gyp ERR! cwd /home/intel/owt-server/source/agent/video/videoMixer/videoMixer_sw
gyp ERR! node -v v6.17.1
gyp ERR! node-gyp -v v6.0.1
gyp ERR! not ok
child_process.js:516
    throw err;
    ^

Error: Command failed: node-gyp build -j 32 --loglevel=error
    at checkExecSyncError (child_process.js:473:13)
    at execSync (child_process.js:513:13)
    at buildTarget (/home/intel/owt-server/scripts/build.js:132:5)
    at buildList.map (/home/intel/owt-server/scripts/build.js:160:10)
    at Array.map (native)
    at Object.<anonymous> (/home/intel/owt-server/scripts/build.js:155:23)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)

**Comment by nikhilsmsc** [comment]
any update ?

**Comment by starwarfan** [comment]
Have you installed svt-hevc?
You can install it by `scripts/installDeps.sh --only svt_hevc` in latest 4.3.x or master branch.

**Comment by nikhilsmsc** [comment]
hi, 
i am getting below log:

Building addon - internal-io
make: Entering directory '/home/ubuntu/owt-server/source/agent/addons/internalIO/build'
  CXX(target) Release/obj.target/internalIO/addon.o
  CXX(target) Release/obj.target/internalIO/InternalInWrapper.o
In file included from /home/ubuntu/owt-server/source/core/owt_base/InternalSctp.h:10,
                 from ../InternalIOWrapper.h:10,
                 from ../addon.cc:7:
/home/ubuntu/owt-server/source/core/owt_base/SctpTransport.h:17:10: fatal error: usrsctp.h: No such file or directory
   17 | #include "usrsctp.h"
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [internalIO.target.mk:124: Release/obj.target/internalIO/addon.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from /home/ubuntu/.cache/node-gyp/8.15.0/include/node/node.h:63,
                 from ../../../addons/common/MediaFramePipelineWrapper.h:9,
                 from ../InternalInWrapper.h:8,
                 from ../InternalInWrapper.cc:9:
/home/ubuntu/.cache/node-gyp/8.15.0/include/node/v8.h: In static member function ‘static void v8::V8::SetAllowCodeGenerationFromStringsCallback(v8::DeprecatedAllowCodeGenerationFromStringsCallback)’:
/home/ubuntu/.cache/node-gyp/8.15.0/include/node/v8.h:10304:19: warning: cast between incompatible function types from ‘v8::DeprecatedAllowCodeGenerationFromStringsCallback’ {aka ‘bool (*)(v8::Local<v8::Context>)’} to ‘v8::FreshNewAllowCodeGenerationFromStringsCallback’ {aka ‘bool (*)(v8::Local<v8::Context>, v8::Local<v8::String>)’} [-Wcast-function-type]
10304 |           callback));
      |                   ^
/home/ubuntu/.cache/node-gyp/8.15.0/include/node/v8.h: In static member function ‘static void v8::V8::RemoveGCPrologueCallback(v8::GCCallback)’:
/home/ubuntu/.cache/node-gyp/8.15.0/include/node/v8.h:10349:53: warning: cast between incompatible function types from ‘v8::GCCallback’ {aka ‘void (*)(v8::GCType, v8::GCCallbackFlags)’} to ‘v8::Isolate::GCCallback’ {aka ‘void (*)(v8::Isolate*, v8::GCType, v8::GCCallbackFlags)’} [-Wcast-function-type]
10349 |       reinterpret_cast<Isolate::GCCallback>(callback));
      |                                                     ^
/home/ubuntu/.cache/node-gyp/8.15.0/include/node/v8.h: In static member function ‘static void v8::V8::RemoveGCEpilogueCallback(v8::GCCallback)’:
/home/ubuntu/.cache/node-gyp/8.15.0/include/node/v8.h:10356:53: warning: cast between incompatible function types from ‘v8::GCCallback’ {aka ‘void (*)(v8::GCType, v8::GCCallbackFlags)’} to ‘v8::Isolate::GCCallback’ {aka ‘void (*)(v8::Isolate*, v8::GCType, v8::GCCallbackFlags)’} [-Wcast-function-type]
10356 |       reinterpret_cast<Isolate::GCCallback>(callback));

/home/ubuntu/.cache/node-gyp/8.15.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/home/ubuntu/.cache/node-gyp/8.15.0/include/node/node_object_wrap.h:85:78:   required from here
/home/ubuntu/.cache/node-gyp/8.15.0/include/node/v8.h:9313:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
 9313 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: Leaving directory '/home/ubuntu/owt-server/source/agent/addons/internalIO/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/.nvm/versions/node/v8.15.0/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 5.6.13-050613-lowlatency
gyp ERR! command "/home/ubuntu/.nvm/versions/node/v8.15.0/bin/node" "/home/ubuntu/.nvm/versions/node/v8.15.0/bin/node-gyp" "rebuild" "-j" "2" "--loglevel=error"
gyp ERR! cwd /home/ubuntu/owt-server/source/agent/addons/internalIO
gyp ERR! node -v v8.15.0
gyp ERR! node-gyp -v v7.0.0
gyp ERR! not ok
child_process.js:650
    throw err;
    ^

Error: Command failed: node-gyp rebuild -j 2 --loglevel=error
