### ISSUE TITLE
Create token error with "ssl"

### ISSUE THREAD

**Issue by qzn928** [open-webrtc-toolkit/owt-server#384]
When I creating a token , return a error:
`
{"error":{"code":2001,"message":"TypeError Cannot read property 'ssl' of undefined"}} at https://owt.com/5dce6b42320c401cb2ef165a/tokens (HTTP status: 500)
`
the nuve log is:
`2019-12-03 08:46:31.616  - WARN: Nuve - TypeError: Cannot read property 'ssl' of undefined
    at /var/www/Release-v4.1/nuve/resource/tokensResource.js:1:984
    at Object.callback (/var/www/Release-v4.1/nuve/cloudHandler.js:1:630)
    at Object.exports.callRpc (/var/www/Release-v4.1/nuve/rpc/rpc.js:1:1186)
    at t (/var/www/Release-v4.1/nuve/cloudHandler.js:1:401)
    at Object.exports.schedulePortal (/var/www/Release-v4.1/nuve/cloudHandler.js:1:649)
    at generateToken (/var/www/Release-v4.1/nuve/resource/tokensResource.js:1:922)
    at exports.create (/var/www/Release-v4.1/nuve/resource/tokensResource.js:1:1360)
    at Layer.handle [as handle_request] (/var/www/Release-v4.1/nuve/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/Release-v4.1/nuve/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/var/www/Release-v4.1/nuve/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/www/Release-v4.1/nuve/node_modules/express/lib/router/layer.js:95:5)
    at /var/www/Release-v4.1/nuve/node_modules/express/lib/router/index.js:281:22
    at param (/var/www/Release-v4.1/nuve/node_modules/express/lib/router/index.js:354:14)
    at param (/var/www/Release-v4.1/nuve/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/var/www/Release-v4.1/nuve/node_modules/express/lib/router/index.js:410:3)
    at next (/var/www/Release-v4.1/nuve/node_modules/express/lib/router/index.js:275:10)`

**Comment by MrSmith87** [comment]
I am also facing the same issue with v4.3.
Any update on this?

**Comment by starwarfan** [comment]
If this issue can be reproduced, edit "log4js_configuration" file under "cluster_manager" directory, change the "ClusterManager" from "INFO" to "DEBUG", and provide us the log when the problem occurs.

**Comment by MrSmith87** [comment]
But I am running the server as a standalone node and not in a cluster. Shall I still check the logs?

**Comment by starwarfan** [comment]
Check the logs, this can help.

**Comment by MrSmith87** [comment]
Here are the logs, though rabbitMq is running fine :
2020-01-09 09:49:53.096  - INFO: AmqpClient - Connection to rabbitMQ server error { Error: read ECONNRESET
    at TCP.onread (net.js:622:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
2020-01-09 09:49:57.101  - INFO: AmqpClient - Connection to rabbitMQ server error { Error: read ECONNRESET
    at TCP.onread (net.js:622:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
2020-01-09 09:50:01.107  - INFO: AmqpClient - Connection to rabbitMQ server error { Error: read ECONNRESET
    at TCP.onread (net.js:622:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
2020-01-09 09:50:05.112  - INFO: AmqpClient - Connection to rabbitMQ server error { Error: read ECONNRESET
    at TCP.onread (net.js:622:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
2020-01-09 09:50:09.117  - INFO: AmqpClient - Connection to rabbitMQ server error { Error: read ECONNRESET
    at TCP.onread (net.js:622:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
2020-01-09 09:50:13.122  - INFO: AmqpClient - Connection to rabbitMQ server error { Error: read ECONNRESET
    at TCP.onread (net.js:622:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
2020-01-09 09:50:17.128  - INFO: AmqpClient - Connection to rabbitMQ server error { Error: read ECONNRESET
    at TCP.onread (net.js:622:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
2020-01-09 09:50:21.133  - INFO: AmqpClient - Connection to rabbitMQ server error { Error: read ECONNRESET
    at TCP.onread (net.js:622:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }

I ran :  bin/init-rabbitmq.sh
output : Rabbitmq-server already running

**Comment by MrSmith87** [comment]
I think the problem was due to the fact that I had changed the users for both rabbitMq and mongodb, and specified my own. Once I re-initialised the server and did the setup again, following the same instructions with default mongo and rabbitMq users, the error was gone.
