### ISSUE TITLE
Get "500 Internal Server Error" when call api resource /v1/rooms/{roomId}/recordings

### ISSUE THREAD

**Issue by bibitoo** [open-webrtc-toolkit/owt-server#476]
When I post request to /v1/rooms/{roomId}/recordings, I get "500 Internal Server Error" response. 
Manage_api module log is 
`INFO: RequestHandler - RPC fail error Access timeout`
There are no extra message in recording-agent.stdout log file.
The management_api log file log4js_configuration.json levels has been change to :
`
    "RequestHandler": "DEBUG",
    "RPCPublic": "DEBUG",
    "RPC": "DEBUG",
`
But There are still no extra error message.
How could I get the detail error message and fix this?

ex:I add ManagementServer level to DEBUG, and got the error message:
`
EBUG: ManagementServer - { CloudError: RPC:addServerSideSubscription failed
    at Object.callback (/opt/owt-server-4.3/dist/management_api/requestHandler.js:317:33)
    at /opt/owt-server-4.3/dist/management_api/rpc/rpc.js:57:65
    at Message.<anonymous> (/opt/owt-server-4.3/dist/management_api/node_modules/amqp/lib/queue.js:209:28)
    at emitNone (events.js:106:13)
    at Message.emit (events.js:208:7)
    at Queue._onContent (/opt/owt-server-4.3/dist/management_api/node_modules/amqp/lib/queue.js:550:25)
    at AMQPParser.self.parser.onContent (/opt/owt-server-4.3/dist/management_api/node_modules/amqp/lib/connection.js:142:32)
    at frameEnd (/opt/owt-server-4.3/dist/management_api/node_modules/amqp/lib/parser.js:101:18)
    at frame (/opt/owt-server-4.3/dist/management_api/node_modules/amqp/lib/parser.js:79:14)
    at header (/opt/owt-server-4.3/dist/management_api/node_modules/amqp/lib/parser.js:65:14)
    at frameEnd (/opt/owt-server-4.3/dist/management_api/node_modules/amqp/lib/parser.js:112:16)
    at frame (/opt/owt-server-4.3/dist/management_api/node_modules/amqp/lib/parser.js:79:14)
    at header (/opt/owt-server-4.3/dist/management_api/node_modules/amqp/lib/parser.js:65:14)
    at frameEnd (/opt/owt-server-4.3/dist/management_api/node_modules/amqp/lib/parser.js:112:16)
    at frame (/opt/owt-server-4.3/dist/management_api/node_modules/amqp/lib/parser.js:79:14)
    at AMQPParser.header [as parse] (/opt/owt-server-4.3/dist/management_api/node_modules/amqp/lib/parser.js:65:14)
  name: 'CloudError',
  status: 500,
  code: 1301,
  data: 
   { error: { code: 1301, message: 'RPC:addServerSideSubscription failed' } } }
`
But the message of cluster is OK.
I'm still not know how to fix the CloudError.
ex2: rpc call for conference agent method addServerSideSubscription, but the console of conference_agent module output is OK.
`starting conference-agent, stdout -> /opt/owt-server-4.3/dist/logs/conference-agent.stdout
2020-04-24 07:53:37.694  - INFO: AmqpClient - Connecting to rabbitMQ server OK, options: { host: 'localhost', port: 5672 }
2020-04-24 07:53:37.725  - INFO: WorkingAgent - conference agent join cluster ok.
2020-04-24 07:53:37.730  - INFO: ClusterWorker - Join cluster owt-cluster OK.
2020-04-24 07:53:37.734  - INFO: WorkingAgent - as rpc server ok.
2020-04-24 07:53:37.735  - INFO: WorkingAgent - as monitoring target ok.`

**Comment by bibitoo** [comment]
I build and install owt-server at difference directory cause node manager error. Still not fix this, I reinstall os and rebuild owt-server and it work now.
