### ISSUE TITLE
Unable to install owt-server

### ISSUE THREAD

**Issue by kiran-kalyanam** [open-webrtc-toolkit/owt-server#488]
Hello, 

I have downloaded the owt-server-master.zip file and am trying to host it in a VM in Google Cloud. My VM is running Ubuntu 18. I am facing few issues. Appreciate your help.

Unzipped the zip file and ran the 

sudo scripts/installDepsUnattended.sh

After that, ran:

sudo scripts/build.js -t all --check

Downloaded and unzipped OWT client from https://github.com/open-webrtc-toolkit/owt-client-javascript

Built it as suggested in the link (used sudo for all commands)

sudo scripts/pack.js -t all --install-module --app-path ${webrtc-javascript-sdk-sample-conference-dist}

Replaced ${webrtc-javascript-sdk-sample-conference-dist} with the dist folder of the owt client

Now, here is where my problem starts. To run the next command:

./bin/init-all.sh --deps

I could not see a bin folder anywhere.  I have searched for the init-all.sh file and no luck.

I am sure I am missing a very minor stuff. Appreciate your help.

Wishes,
Kiran

**Comment by kiran-kalyanam** [comment]
Can somebody please help me in resolving this issue?  Thanks in advance.

**Comment by starwarfan** [comment]
Hi, it seems that you packing is not successful. Were there any errors during your packing process?

**Comment by kiran-kalyanam** [comment]
Hi @starwarfan,

Thank you for your response. Today I have deleted my old VM and created a fresh VM on Google Cloud and started the build process again.  

sudo scripts/installDepsUnattended.sh

Executed without any problem. However, 

scripts/build.js -t all --check

is throwing the following error:

Following targets will be built:
 video-mixer-sw 
 video-transcoder-sw 
 video-analyzer-sw 
 internal-io 
 logger 
 media-frame-multicaster 
 audio 
 webrtc-conn 
 webrtc-frame 
 avstream 
 sip 
 video-mixer-msdk 
 video-transcoder-msdk 
Building addon- video-mixer-sw
module.js:550
    throw err;
    ^

Error: Cannot find module 'graceful-fs'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/share/node-gyp/lib/node-gyp.js:12:10)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
child_process.js:650
    throw err;
    ^

Error: Command failed: node-gyp configure --loglevel=error
    at checkExecSyncError (child_process.js:607:13)
    at execSync (child_process.js:647:13)
    at buildTarget (/home/kvrnkiran/owt-server-master/scripts/build.js:132:5)
    at buildList.map (/home/kvrnkiran/owt-server-master/scripts/build.js:161:10)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/home/kvrnkiran/owt-server-master/scripts/build.js:156:23)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)

Tried all options to install graceful-fs and had the same error. I see graceful-fs is available on my system.

locate graceful-fs
/home/user12/.nvm/versions/node/v8.15.0/lib/node_modules/jsdoc/node_modules/graceful-fs
/home/user12/.nvm/versions/node/v8.15.0/lib/node_modules/jsdoc/node_modules/graceful-fs/LICENSE
/home/user12/.nvm/versions/node/v8.15.0/lib/node_modules/jsdoc/node_modules/graceful-fs/README.md
/home/user12/.nvm/versions/node/v8.15.0/lib/node_modules/jsdoc/node_modules/graceful-fs/clone.js
/home/user12/.nvm/versions/node/v8.15.0/lib/node_modules/jsdoc/node_modules/graceful-fs/graceful-fs.js
/home/user12/.nvm/versions/node/v8.15.0/lib/node_modules/jsdoc/node_modules/graceful-fs/legacy-streams.js
/home/user12/.nvm/versions/node/v8.15.0/lib/node_modules/jsdoc/node_modules/graceful-fs/package.json
/home/user12/.nvm/versions/node/v8.15.0/lib/node_modules/jsdoc/node_modules/graceful-fs/polyfills.js
/home/user12/.nvm/versions/node/v8.15.0/lib/node_modules/node-gyp/node_modules/graceful-fs
/home/user12/.nvm/versions/node/v8.15.0/lib/node_modules/node-gyp/node_modules/graceful-fs/LICENSE
/home/user12/.nvm/versions/node/v8.15.0/lib/node_modules/node-gyp/node_modules/graceful-fs/README.md
/home/user12/.nvm/versions/node/v8.15.0/lib/node_modules/node-gyp/node_modules/graceful-fs/clone.js
/home/user12/.nvm/versions/node/v8.15.0/lib/node_modules/node-gyp/node_modules/graceful-fs/graceful-fs.js
/home/user12/.nvm/versions/node/v8.15.0/lib/node_modules/node-gyp/node_modules/graceful-fs/legacy-streams.js
/home/user12/.nvm/versions/node/v8.15.0/lib/node_modules/node-gyp/node_modules/graceful-fs/package.json
/home/user12/.nvm/versions/node/v8.15.0/lib/node_modules/node-gyp/node_modules/graceful-fs/polyfills.js
/home/user12/.nvm/versions/node/v8.15.0/lib/node_modules/npm/node_modules/graceful-fs
/home/user12/.nvm/versions/node/v8.15.0/lib/node_modules/npm/node_modules/graceful-fs/LICENSE
/home/user12/.nvm/versions/node/v8.15.0/lib/node_modules/npm/node_modules/graceful-fs/README.md
/home/user12/.nvm/versions/node/v8.15.0/lib/node_modules/npm/node_modules/graceful-fs/fs.js
/home/user12/.nvm/versions/node/v8.15.0/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js
/home/user12/.nvm/versions/node/v8.15.0/lib/node_modules/npm/node_modules/graceful-fs/legacy-streams.js
/home/user12/.nvm/versions/node/v8.15.0/lib/node_modules/npm/node_modules/graceful-fs/package.json
/home/user12/.nvm/versions/node/v8.15.0/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js
/usr/lib/node_modules/npm/node_modules/graceful-fs
/usr/lib/node_modules/npm/node_modules/graceful-fs/clone.js
/usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js
/usr/lib/node_modules/npm/node_modules/graceful-fs/legacy-streams.js
/usr/lib/node_modules/npm/node_modules/graceful-fs/package.json
/usr/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js

I ran the installation script with and without sudo, but the same results. Can you please help?

Thanks,
Kiran

**Comment by kiran-kalyanam** [comment]
Found an issue. node-gyp on running throwing the above error. I had installed node-gyp with apt install. Removed it and installed it with npm install node-gyp and the script is going on.  I will keep you updated.  Thank you.

**Comment by kiran-kalyanam** [comment]
Hi @starwarfan,

Made some good progress. Stuck at the last step.  Here are the logs:

user12@intel-streaming-server:~/owt-server-master/dist$ ./bin/start-all.sh 
starting management-api, stdout -> /home/user12/owt-server-master/dist/logs/management-api.stdout
starting cluster-manager, stdout -> /home/user12/owt-server-master/dist/logs/cluster-manager.stdout
starting video-agent, stdout -> /home/user12/owt-server-master/dist/logs/video-agent.stdout
starting audio-agent, stdout -> /home/user12/owt-server-master/dist/logs/audio-agent.stdout
starting analytics-agent, stdout -> /home/user12/owt-server-master/dist/logs/analytics-agent.stdout
starting conference-agent, stdout -> /home/user12/owt-server-master/dist/logs/conference-agent.stdout
starting recording-agent, stdout -> /home/user12/owt-server-master/dist/logs/recording-agent.stdout
starting streaming-agent, stdout -> /home/user12/owt-server-master/dist/logs/streaming-agent.stdout
starting sip-agent, stdout -> /home/user12/owt-server-master/dist/logs/sip-agent.stdout
starting webrtc-agent, stdout -> /home/user12/owt-server-master/dist/logs/webrtc-agent.stdout
starting portal, stdout -> /home/user12/owt-server-master/dist/logs/portal.stdout
starting management-console, stdout -> /home/user12/owt-server-master/dist/logs/management-console.stdout
Start management-console HTTPS server
starting sip-portal, stdout -> /home/user12/owt-server-master/dist/logs/sip-portal.stdout
starting app, stdout -> /home/user12/owt-server-master/dist/logs/app.stdout
module.js:550
    throw err;
    ^

Error: Cannot find module '/home/user12/owt-server-master/dist/apps/current_app'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
user12@intel-streaming-server:~/owt-server-master/dist$ cd apps/
user12@intel-streaming-server:~/owt-server-master/dist/apps$ ls
current_app
user12@intel-streaming-server:~/owt-server-master/dist/apps$ cd current_app/
user12@intel-streaming-server:~/owt-server-master/dist/apps/current_app$ ls
README.md  cert  cipher.js  initcert.js  main.js  node_modules  package-lock.json  package.json  public  rest.js  samplertcservice.js
user12@intel-streaming-server:~/owt-server-master/dist/apps/current_app$ ls -l
total 160
-rw-rw-r--   1 user12 user12   590 Oct 28  2019 README.md
drwxrwxr-x   2 user12 user12  4096 May 10 10:42 cert
-rw-rw-r--   1 user12 user12  1572 Oct 28  2019 cipher.js
-rwxrwxr-x   1 user12 user12  1066 Oct 28  2019 initcert.js
*lrwxrwxrwx   1 user12 user12     9 May 10 10:54 main.js -> undefined*
drwxrwxr-x 101 user12 user12  4096 May 10 10:55 node_modules
-rw-rw-r--   1 user12 user12 40226 May 10 10:55 package-lock.json
-rw-rw-r--   1 user12 user12   540 Oct 28  2019 package.json
drwxrwxr-x   3 user12 user12  4096 May 10 10:42 public
-rw-rw-r--   1 user12 user12 73925 May 10 10:42 rest.js
-rw-rw-r--   1 user12 user12 15707 May 10 11:13 samplertcservice.js

Looks like the following is the problem:

*lrwxrwxrwx   1 user12 user12     9 May 10 10:54 main.js -> undefined*

Appreciate your help.

Kiran

**Comment by kiran-kalyanam** [comment]
Hi,

All the other sh files completed successfully.

For the following command:

./bin/init-all.sh --deps

At the end, there was few prompts for RabbitMQ and MongoDB username and passwords. I gave a random username and password form them:

Update RabbitMQ/MongoDB Account? [No/yes]Update RabbitMQ account?[yes/no]yes
(cluster_manager) Enter username of rabbitmq: kiran
(cluster_manager) Enter password of rabbitmq: done!
Update MongoDB account?[yes/no]yes
(cluster_manager) Enter username of mongodb: kiran
(cluster_manager) Enter password of mongodb: done!

And after the above statement, I got Done!. 

I have executed 

./bin/start-all.sh

And got the error message as mentioned in my previous post.

Thanks a lot for your patience.

Kiran

**Comment by starwarfan** [comment]
Hi, did you have password for these component?
If you have no username/password in default, then please enter 'No' or just enter to pass for updating credentials.
Otherwise, you can perform pack with '-r' option to clean the dist and skip the 'Updating credential' phase next time.

**Comment by kiran-kalyanam** [comment]
Hello @starwarfan,

Thank you for your suggestion. I will check it and will post results here.

Thanks,
Kiran
