### ISSUE TITLE
Warning and error during startup master brach

### ISSUE THREAD

**Issue by nareshinstavc** [open-webrtc-toolkit/owt-server#490]
Dear Team,

we are getting bellow error when startup MCU services in management_api , we used master branch to build and install on Ubuntu 18.04 LTS server

WARNING: The `useMongoClient` option is no longer necessary in mongoose 5.x, please remove it.
    at handleUseMongoClient (/root/owt-server/dist/management_api/node_modules/mongoose/lib/connection.js:860:17)
    at NativeConnection.Connection.openUri (/root/owt-server/dist/management_api/node_modules/mongoose/lib/connection.js:637:7)
    at Mongoose.connect (/root/owt-server/dist/management_api/node_modules/mongoose/lib/index.js:333:15)
    at setupConnection (/root/owt-server/dist/management_api/data_access/index.js:27:12)
    at Object.<anonymous> (/root/owt-server/dist/management_api/data_access/index.js:50:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/owt-server/dist/management_api/auth/serverAuthenticator.js:30:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
(node:6021) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:6021) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:6021) DeprecationWarning: Mongoose: `findOneAndUpdate()` and `findOneAndDelete()` without the `useFindAndModify` option set to false are deprecated. See: https://mongoosejs.com/docs/deprecations.html#findandmodify
(node:6021) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
WARNING: The `useMongoClient` option is no longer necessary in mongoose 5.x, please remove it.
    at handleUseMongoClient (/root/owt-server/dist/management_api/node_modules/mongoose/lib/connection.js:860:17)
    at NativeConnection.Connection.openUri (/root/owt-server/dist/management_api/node_modules/mongoose/lib/connection.js:637:7)
    at Mongoose.connect (/root/owt-server/dist/management_api/node_modules/mongoose/lib/index.js:333:15)
    at setupConnection (/root/owt-server/dist/management_api/data_access/index.js:27:12)
    at Object.<anonymous> (/root/owt-server/dist/management_api/data_access/index.js:50:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/owt-server/dist/management_api/auth/serverAuthenticator.js:30:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
WARNING: The `useMongoClient` option is no longer necessary in mongoose 5.x, please remove it.
    at handleUseMongoClient (/root/owt-server/dist/management_api/node_modules/mongoose/lib/connection.js:860:17)
    at NativeConnection.Connection.openUri (/root/owt-server/dist/management_api/node_modules/mongoose/lib/connection.js:637:7)
    at Mongoose.connect (/root/owt-server/dist/management_api/node_modules/mongoose/lib/index.js:333:15)
    at setupConnection (/root/owt-server/dist/management_api/data_access/index.js:27:12)
    at Object.<anonymous> (/root/owt-server/dist/management_api/data_access/index.js:50:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/owt-server/dist/management_api/auth/serverAuthenticator.js:30:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
WARNING: The `useMongoClient` option is no longer necessary in mongoose 5.x, please remove it.
WARNING: The `useMongoClient` option is no longer necessary in mongoose 5.x, please remove it.
    at handleUseMongoClient (/root/owt-server/dist/management_api/node_modules/mongoose/lib/connection.js:860:17)
    at NativeConnection.Connection.openUri (/root/owt-server/dist/management_api/node_modules/mongoose/lib/connection.js:637:7)
    at Mongoose.connect (/root/owt-server/dist/management_api/node_modules/mongoose/lib/index.js:333:15)
    at setupConnection (/root/owt-server/dist/management_api/data_access/index.js:27:12)
    at Object.<anonymous> (/root/owt-server/dist/management_api/data_access/index.js:50:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/owt-server/dist/management_api/auth/serverAuthenticator.js:30:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at handleUseMongoClient (/root/owt-server/dist/management_api/node_modules/mongoose/lib/connection.js:860:17)
    at NativeConnection.Connection.openUri (/root/owt-server/dist/management_api/node_modules/mongoose/lib/connection.js:637:7)
    at Mongoose.connect (/root/owt-server/dist/management_api/node_modules/mongoose/lib/index.js:333:15)
    at setupConnection (/root/owt-server/dist/management_api/data_access/index.js:27:12)
    at Object.<anonymous> (/root/owt-server/dist/management_api/data_access/index.js:50:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/owt-server/dist/management_api/auth/serverAuthenticator.js:30:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
2020-05-04 16:06:21.025  - INFO: ManagementServer - Worker 6032 started
(node:6032) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:6032) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
2020-05-04 16:06:21.046  - INFO: ManagementServer - Worker 6033 started
2020-05-04 16:06:21.050  - INFO: ManagementServer - Worker 6038 started
(node:6038) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:6038) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
2020-05-04 16:06:21.073  - INFO: ManagementServer - Worker 6039 started
(node:6039) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:6039) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:6033) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:6033) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:6032) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
(node:6033) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
(node:6039) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
(node:6038) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
2020-05-04 16:06:21.393  - INFO: RPC - Connected to rabbitMQ server
2020-05-04 16:06:21.426  - INFO: RPC - Exchange owtRpc is open
2020-05-04 16:06:21.433  - INFO: RPC - Connected to rabbitMQ server
2020-05-04 16:06:21.437  - INFO: RPC - ClientQueue amq.gen--br3u_KH414uGGbtSc6chQ is open
2020-05-04 16:06:21.442  - INFO: RPC - Connected to rabbitMQ server
2020-05-04 16:06:21.454  - INFO: RPC - Connected to rabbitMQ server
2020-05-04 16:06:21.464  - INFO: RPC - Exchange owtRpc is open
2020-05-04 16:06:21.465  - INFO: RPC - Exchange owtRpc is open
2020-05-04 16:06:21.471  - INFO: RPC - ClientQueue amq.gen-UPqE4XEhZV0XQY-hTUZn_w is open
2020-05-04 16:06:21.472  - INFO: RPC - ClientQueue amq.gen-KcXPuJF5JbCaXlRBREQRQQ is open
2020-05-04 16:06:21.478  - INFO: RPC - Exchange owtRpc is open
2020-05-04 16:06:21.485  - INFO: RPC - ClientQueue amq.gen-TSeKlIcvEXmIQ-FB40_5kQ is open

**Comment by starwarfan** [comment]
Hi, the deprecation warning is removed in latest master. Refer to #481
