### ISSUE TITLE
scripts/build.js -t mcu --check Error

### ISSUE THREAD

**Issue by lanyan90** [open-webrtc-toolkit/owt-server#553]
ubuntu18.04，scripts/build.js -t mcu --check，Error info:
root@ubuntu:/opt/owt-server-4.3# ./scripts/build.js -t mcu --check
/opt/owt-server-4.3/build/libdeps/build/lib/pkgconfig:/opt/owt-server-4.3/build/libdeps/build/lib64/pkgconfig:
Following targets will be built:
 video-mixer-sw 
 video-transcoder-sw 
 video-analyzer-sw 
 internal-io 
 logger 
 media-frame-multicaster 
 audio 
 webrtc 
 avstream 
 sip 
Building addon - video-mixer-sw
make: Entering directory '/opt/owt-server-4.3/source/agent/video/videoMixer/videoMixer_sw/build'
make: Nothing to be done for 'all'.
make: Leaving directory '/opt/owt-server-4.3/source/agent/video/videoMixer/videoMixer_sw/build'
Finish addon - video-mixer-sw
Building addon - video-transcoder-sw
make: Entering directory '/opt/owt-server-4.3/source/agent/video/videoTranscoder/videoTranscoder_sw/build'
make: Nothing to be done for 'all'.
make: Leaving directory '/opt/owt-server-4.3/source/agent/video/videoTranscoder/videoTranscoder_sw/build'
Finish addon - video-transcoder-sw
Building addon - video-analyzer-sw
make: Entering directory '/opt/owt-server-4.3/source/agent/video/videoTranscoder/videoAnalyzer_sw/build'
make: Nothing to be done for 'all'.
make: Leaving directory '/opt/owt-server-4.3/source/agent/video/videoTranscoder/videoAnalyzer_sw/build'
Finish addon - video-analyzer-sw
Building addon - internal-io
make: Entering directory '/opt/owt-server-4.3/source/agent/addons/internalIO/build'
make: Nothing to be done for 'all'.
make: Leaving directory '/opt/owt-server-4.3/source/agent/addons/internalIO/build'
Finish addon - internal-io
Building addon - logger
make: Entering directory '/opt/owt-server-4.3/source/agent/addons/logger/build'
make: Nothing to be done for 'all'.
make: Leaving directory '/opt/owt-server-4.3/source/agent/addons/logger/build'
Finish addon - logger
Building addon - media-frame-multicaster
make: Entering directory '/opt/owt-server-4.3/source/agent/addons/mediaFrameMulticaster/build'
make: Nothing to be done for 'all'.
make: Leaving directory '/opt/owt-server-4.3/source/agent/addons/mediaFrameMulticaster/build'
Finish addon - media-frame-multicaster
Building addon - audio
make: Entering directory '/opt/owt-server-4.3/source/agent/audio/audioMixer/build'
make: Nothing to be done for 'all'.
make: Leaving directory '/opt/owt-server-4.3/source/agent/audio/audioMixer/build'
Finish addon - audio
Building addon - webrtc
make: Entering directory '/opt/owt-server-4.3/source/agent/webrtc/webrtcLib/build'
  CXX(target) Release/obj.target/webrtc/erizo/src/erizo/dtls/DtlsSocket.o
  CC(target) Release/obj.target/webrtc/erizo/src/erizo/dtls/bf_dwrap.o
  CXX(target) Release/obj.target/webrtc/../../addons/common/NodeEventRegistry.o
  CXX(target) Release/obj.target/webrtc/../../../core/owt_base/AudioFrameConstructor.o
../erizo/src/erizo/dtls/bf_dwrap.c:18:1: error: variable ‘methods_dwrap’ has initializer but incomplete type
 static BIO_METHOD methods_dwrap = {
 ^~~~~~
../erizo/src/erizo/dtls/bf_dwrap.c:7:30: warning: excess elements in struct initializer
 #define BIO_TYPE_DWRAP       (50 | 0x0400 | 0x0200)
                              ^
../erizo/src/erizo/dtls/bf_dwrap.c:19:3: note: in expansion of macro ‘BIO_TYPE_DWRAP’
   BIO_TYPE_DWRAP,
   ^~~~~~~~~~~~~~
../erizo/src/erizo/dtls/bf_dwrap.c:7:30: note: (near initialization for ‘methods_dwrap’)
 #define BIO_TYPE_DWRAP       (50 | 0x0400 | 0x0200)
                              ^
../erizo/src/erizo/dtls/bf_dwrap.c:19:3: note: in expansion of macro ‘BIO_TYPE_DWRAP’
   BIO_TYPE_DWRAP,
   ^~~~~~~~~~~~~~
../erizo/src/erizo/dtls/bf_dwrap.c:20:3: warning: excess elements in struct initializer
   "dtls_wrapper",
   ^~~~~~~~~~~~~~
../erizo/src/erizo/dtls/bf_dwrap.c:20:3: note: (near initialization for ‘methods_dwrap’)
../erizo/src/erizo/dtls/bf_dwrap.c:21:3: warning: excess elements in struct initializer
   dwrap_write,
   ^~~~~~~~~~~
../erizo/src/erizo/dtls/bf_dwrap.c:21:3: note: (near initialization for ‘methods_dwrap’)
../erizo/src/erizo/dtls/bf_dwrap.c:22:3: warning: excess elements in struct initializer
   dwrap_read,
   ^~~~~~~~~~
../erizo/src/erizo/dtls/bf_dwrap.c:22:3: note: (near initialization for ‘methods_dwrap’)
../erizo/src/erizo/dtls/bf_dwrap.c:23:3: warning: excess elements in struct initializer
   dwrap_puts,
   ^~~~~~~~~~
../erizo/src/erizo/dtls/bf_dwrap.c:23:3: note: (near initialization for ‘methods_dwrap’)
../erizo/src/erizo/dtls/bf_dwrap.c:24:3: warning: excess elements in struct initializer
   dwrap_gets,
   ^~~~~~~~~~
../erizo/src/erizo/dtls/bf_dwrap.c:24:3: note: (near initialization for ‘methods_dwrap’)
../erizo/src/erizo/dtls/bf_dwrap.c:25:3: warning: excess elements in struct initializer
   dwrap_ctrl,
   ^~~~~~~~~~
../erizo/src/erizo/dtls/bf_dwrap.c:25:3: note: (near initialization for ‘methods_dwrap’)
../erizo/src/erizo/dtls/bf_dwrap.c:26:3: warning: excess elements in struct initializer
   dwrap_new,
   ^~~~~~~~~
../erizo/src/erizo/dtls/bf_dwrap.c:26:3: note: (near initialization for ‘methods_dwrap’)
../erizo/src/erizo/dtls/bf_dwrap.c:27:3: warning: excess elements in struct initializer
   dwrap_free,
   ^~~~~~~~~~
../erizo/src/erizo/dtls/bf_dwrap.c:27:3: note: (near initialization for ‘methods_dwrap’)
../erizo/src/erizo/dtls/bf_dwrap.c:28:3: warning: excess elements in struct initializer
   dwrap_callback_ctrl
   ^~~~~~~~~~~~~~~~~~~
../erizo/src/erizo/dtls/bf_dwrap.c:28:3: note: (near initialization for ‘methods_dwrap’)
In file included from /root/.cache/node-gyp/10.15.3/include/node/openssl/bio.h:20:0,
                 from ../erizo/src/erizo/dtls/bf_dwrap.c:3:
../erizo/src/erizo/dtls/bf_dwrap.c: In function ‘dwrap_new’:
../erizo/src/erizo/dtls/bf_dwrap.c:41:48: error: ‘BIO_F_BUFFER_CTX’ undeclared (first use in this function); did you mean ‘BIO_F_BUFFER_C
   BIO_F_DWRAP_CTX *ctx = OPENSSL_malloc(sizeof(BIO_F_BUFFER_CTX));
                                                ^
/root/.cache/node-gyp/10.15.3/include/node/openssl/crypto.h:126:23: note: in definition of macro ‘OPENSSL_malloc’
         CRYPTO_malloc(num, OPENSSL_FILE, OPENSSL_LINE)
                       ^~~
../erizo/src/erizo/dtls/bf_dwrap.c:41:48: note: each undeclared identifier is reported only once for each function it appears in
   BIO_F_DWRAP_CTX *ctx = OPENSSL_malloc(sizeof(BIO_F_BUFFER_CTX));
                                                ^
/root/.cache/node-gyp/10.15.3/include/node/openssl/crypto.h:126:23: note: in definition of macro ‘OPENSSL_malloc’
         CRYPTO_malloc(num, OPENSSL_FILE, OPENSSL_LINE)
                       ^~~
../erizo/src/erizo/dtls/bf_dwrap.c:46:5: error: dereferencing pointer to incomplete type ‘BIO {aka struct bio_st}’
   bi->init = 1;
     ^~
../erizo/src/erizo/dtls/bf_dwrap.c: At top level:
../erizo/src/erizo/dtls/bf_dwrap.c:18:19: error: storage size of ‘methods_dwrap’ isn’t known
 static BIO_METHOD methods_dwrap = {
                   ^~~~~~~~~~~~~
webrtc.target.mk:213: recipe for target 'Release/obj.target/webrtc/erizo/src/erizo/dtls/bf_dwrap.o' failed
make: *** [Release/obj.target/webrtc/erizo/src/erizo/dtls/bf_dwrap.o] Error 1
make: *** Waiting for unfinished jobs....
../erizo/src/erizo/dtls/DtlsSocket.cpp: In constructor ‘dtls::DtlsSocket::DtlsSocket(dtls::DtlsSocketContext*, dtls::DtlsSocket::SocketTy
../erizo/src/erizo/dtls/DtlsSocket.cpp:35:7: error: invalid use of incomplete type ‘SSL {aka struct ssl_st}’
   mSsl->ctx = mContext;
       ^~
In file included from /root/.cache/node-gyp/10.15.3/include/node/openssl/rand.h:14:0,
                 from ../erizo/src/erizo/dtls/DtlsSocket.h:9,
                 from ../erizo/src/erizo/dtls/DtlsSocket.cpp:1:
/root/.cache/node-gyp/10.15.3/include/node/openssl/ossl_typ.h:144:16: note: forward declaration of ‘SSL {aka struct ssl_st}’
 typedef struct ssl_st SSL;
                ^~~~~~
../erizo/src/erizo/dtls/DtlsSocket.cpp:36:7: error: invalid use of incomplete type ‘SSL {aka struct ssl_st}’
   mSsl->session_ctx = mContext;
       ^~
In file included from /root/.cache/node-gyp/10.15.3/include/node/openssl/rand.h:14:0,
                 from ../erizo/src/erizo/dtls/DtlsSocket.h:9,
                 from ../erizo/src/erizo/dtls/DtlsSocket.cpp:1:
/root/.cache/node-gyp/10.15.3/include/node/openssl/ossl_typ.h:144:16: note: forward declaration of ‘SSL {aka struct ssl_st}’
 typedef struct ssl_st SSL;
                ^~~~~~
webrtc.target.mk:219: recipe for target 'Release/obj.target/webrtc/erizo/src/erizo/dtls/DtlsSocket.o' failed
make: *** [Release/obj.target/webrtc/erizo/src/erizo/dtls/DtlsSocket.o] Error 1
make: Leaving directory '/opt/owt-server-4.3/source/agent/webrtc/webrtcLib/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-99-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "build" "-j" "4" "--loglevel=error"
gyp ERR! cwd /opt/owt-server-4.3/source/agent/webrtc/webrtcLib
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v7.0.0
gyp ERR! not ok 
child_process.js:656
    throw err;
    ^

Error: Command failed: node-gyp build -j 4 --loglevel=error
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:653:13)
    at buildTarget (/opt/owt-server-4.3/scripts/build.js:132:5)
    at buildList.map (/opt/owt-server-4.3/scripts/build.js:160:10)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/opt/owt-server-4.3/scripts/build.js:155:23)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)

**Comment by keycodingyfq** [comment]
might be the below step can help you
first uninstall gyp  and then reinstall gyp and select version 6.1.0
