### ISSUE TITLE
Problem with build script

### ISSUE THREAD

**Issue by myaspm** [open-webrtc-toolkit/owt-server#639]
Hi,

While following instructions, i'm stuck at the ```scripts/build.js -t all --check .``` step.

I'm getting the following error:

```
root@test:~/owt-server# scripts/build.js -t all --check .
/root/owt-server/build/libdeps/build/lib/pkgconfig:/root/owt-server/build/libdeps/build/lib64/pkgconfig:
Following targets will be built:
 video-mixer-sw
 video-transcoder-sw
 video-analyzer-sw
 internal-io
 logger
 media-frame-multicaster
 audio
 webrtc-conn
 webrtc-frame
 avstream
 sip
 video-mixer-msdk
 video-transcoder-msdk
Building addon - video-mixer-sw
make: Entering directory '/root/owt-server/source/agent/video/videoMixer/videoMixer_sw/build'
  CXX(target) Release/obj.target/videoMixer-sw/../addon.o
In file included from ../../addon.cc:5:0:
../../VideoMixerWrapper.h:19:24: error: ‘v8::Handle’ has not been declared
   static void Init(v8::Handle<v8::Object>, v8::Handle<v8::Object>);
                        ^~~~~~
../../VideoMixerWrapper.h:19:30: error: expected ‘,’ or ‘...’ before ‘<’ token
   static void Init(v8::Handle<v8::Object>, v8::Handle<v8::Object>);
                              ^
videoMixer-sw.target.mk:146: recipe for target 'Release/obj.target/videoMixer-sw/../addon.o' failed
make: *** [Release/obj.target/videoMixer-sw/../addon.o] Error 1
make: Leaving directory '/root/owt-server/source/agent/video/videoMixer/videoMixer_sw/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 4.15.0-115-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "build" "-j" "1" "--loglevel=error"
gyp ERR! cwd /root/owt-server/source/agent/video/videoMixer/videoMixer_sw
gyp ERR! node -v v14.9.0
gyp ERR! node-gyp -v v7.1.0
gyp ERR! not ok
child_process.js:655
    throw err;
    ^

Error: Command failed: node-gyp build -j 1 --loglevel=error
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at buildTarget (/root/owt-server/scripts/build.js:133:5)
    at /root/owt-server/scripts/build.js:161:10
    at Array.map (<anonymous>)
    at Object.<anonymous> (/root/owt-server/scripts/build.js:156:23)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 479,
  stdout: null,
  stderr: null
}
```

Ubuntu 18.04, completely clean, only install nodejs.

**Comment by starwarfan** [comment]
Hi
Please use the matched node version. v10 for latest master, v8 for old braches.
