### ISSUE TITLE
build error   find: 'erizo/src/erizo/dtls': Not a directory

### ISSUE THREAD

**Issue by beijing-penguin** [open-webrtc-toolkit/owt-server#646]
ubuntu18.04  
owt-server-master

![image](https://user-images.githubusercontent.com/10703753/93159606-1f66ff00-f741-11ea-95bc-2a0c9ec5c1de.png)

Finish addon - media-frame-multicaster
Building addon - audio
make: Entering directory '/root/owt/penguin-media-server/source/agent/audio/audioMixer/build'
make: Nothing to be done for 'all'.
make: Leaving directory '/root/owt/penguin-media-server/source/agent/audio/audioMixer/build'
Finish addon - audio
Building addon - webrtc-conn
find: 'erizo/src/erizo/dtls': Not a directory
gyp: Call to 'find erizo/src/erizo/dtls -name "*.cpp"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/root/.nvm/versions/node/v10.21.0/lib/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-29-generic
gyp ERR! command "/root/.nvm/versions/node/v10.21.0/bin/node" "/root/.nvm/versions/node/v10.21.0/bin/node-gyp" "configure" "--loglevel=error"
gyp ERR! cwd /root/owt/penguin-media-server/source/agent/webrtc/rtcConn
gyp ERR! node -v v10.21.0
gyp ERR! node-gyp -v v7.1.0
gyp ERR! not ok 
child_process.js:669
    throw err;
    ^

Error: Command failed: node-gyp configure --loglevel=error
    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at buildTarget (/root/owt/penguin-media-server/scripts/build.js:132:5)
    at buildList.map (/root/owt/penguin-media-server/scripts/build.js:161:10)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/root/owt/penguin-media-server/scripts/build.js:156:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

**Comment by beijing-penguin** [comment]
maybe some script need "chmod +x"
