### ISSUE TITLE
video-agent crash

### ISSUE THREAD

**Issue by steven-tianx** [open-webrtc-toolkit/owt-server#686]
environment:
centos7.3
owt-server 4.3.0 

the crash log for video-agent:
2020-11-04 16:35:54.707  - DEBUG: VideoNode - linkup, connectionId: 248281071364214720@webrtc-a50219ae82db3658efc3@10.244.47.89_41 video_stream_id: 248281071364214720
2020-11-04 16:36:52.387  - DEBUG: VideoNode - unsubscribe, connectionId: 248281071364214720@webrtc-a50219ae82db3658efc3@10.244.47.89_41
2020-11-04 16:37:03.880  - DEBUG: VideoNode - generate, codec: h264_CB resolution: unspecified framerate: unspecified bitrate: unspecified keyFrameInterval: unspecified
2020-11-04 16:37:03.881  - DEBUG: VideoNode - addOutput: codec h264_cb resolution: { width: 0, height: 0 } framerate: 30 bitrate: 64000 keyFrameInterval: 1000
2020-11-04 16:37:03.899  - DEBUG: VideoNode - addOutput ok, stream_id: 664211569271886000
2020-11-04 16:37:03.908  - DEBUG: VideoNode - subscribe, connectionId: 664211569271886000@webrtc-a50219ae82db3658efc3@10.244.47.89_41 connectionType: internal options: {"controller":"conference-039dc50e990d294ce6c3@10.244.36.236_31","ip":"10.244.47.89","port":44830}
2020-11-04 16:37:03.911  - DEBUG: VideoNode - linkup, connectionId: 664211569271886000@webrtc-a50219ae82db3658efc3@10.244.47.89_41 video_stream_id: 664211569271886000
*** Error in `node': free(): invalid pointer: 0x00007f3360001048 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7c503)[0x7f33fea19503]
/opt/Release-prexg/video_agent/internalIO/build/Release/internalIO.node(_ZN8owt_base12RawTransportILNS_8ProtocolE0EE12writeHandlerERKN5boost6system10error_codeEm+0x2b6)[0x7f33ecee6036]
/opt/Release-prexg/video_agent/internalIO/build/Release/internalIO.node(_ZN5boost4asio6detail8write_opINS0_19basic_stream_socketINS0_2ip3tcpENS0_21stream_socket_serviceIS5_EEEENS0_17mutable_buffers_1ENS1_14transfer_all_tENS_3_bi6bind_tIvNS_4_mfi3mf2IvN8owt_base12RawTransportILNSF_8ProtocolE0EEERKNS_6system10error_codeEmEENSB_5list3INSB_5valueIPSI_EEPFNS_3argILi1EEEvEPFNSS_ILi2EEEvEEEEEEclESM_mi+0x20a)[0x7f33ecee5a8a]
/opt/Release-prexg/video_agent/internalIO/build/Release/internalIO.node(_ZN5boost4asio6detail23reactive_socket_send_opINS0_17mutable_buffers_1ENS1_8write_opINS0_19basic_stream_socketINS0_2ip3tcpENS0_21stream_socket_serviceIS7_EEEES3_NS1_14transfer_all_tENS_3_bi6bind_tIvNS_4_mfi3mf2IvN8owt_base12RawTransportILNSG_8ProtocolE0EEERKNS_6system10error_codeEmEENSC_5list3INSC_5valueIPSJ_EEPFNS_3argILi1EEEvEPFNST_ILi2EEEvEEEEEEEE11do_completeEPNS1_15task_io_serviceEPNS1_25task_io_service_operationESN_m+0x154)[0x7f33ecee6334]
/opt/Release-prexg/video_agent/internalIO/build/Release/internalIO.node(_ZN5boost4asio6detail15task_io_service3runERNS_6system10error_codeE+0x49b)[0x7f33ecedfd4b]
/opt/Release-prexg/video_agent/internalIO/build/Release/internalIO.node(_ZN5boost4asio10io_service3runEv+0x2f)[0x7f33ecee0d7f]
/lib64/libboost_thread-mt.so.1.53.0(+0xd27a)[0x7f33ed31d27a]
/lib64/libpthread.so.0(+0x7dc5)[0x7f33fed65dc5]
/lib64/libc.so.6(clone+0x6d)[0x7f33fea9476d]
======= Memory map: ========
00400000-01f68000 r-xp 00000000 fd:03 2134684                            /home/node-v8.15.0/bin/node
02168000-02183000 rw-p 01b68000 fd:03 2134684                            /home/node-v8.15.0/bin/node
02183000-0219a000 rw-p 00000000 00:00 0 
02abd000-03a92000 rw-p 00000000 00:00 0                                  [heap]

The back trace in gdb video-agent:(gdb) bt
#0  0x00007f33fe9d21d7 in raise () from /lib64/libc.so.6
#1  0x00007f33fe9d38c8 in abort () from /lib64/libc.so.6
#2  0x00007f33fea11f07 in __libc_message () from /lib64/libc.so.6
#3  0x00007f33fea19503 in _int_free () from /lib64/libc.so.6
#4  0x00007f33ecee6036 in deallocate (this=0x7f33d4ff1620, __p=<optimized out>) at /usr/local/include/c++/6.2.0/ext/new_allocator.h:110
#5  deallocate (__a=..., __n=<optimized out>, __p=<optimized out>) at /usr/local/include/c++/6.2.0/bits/alloc_traits.h:442
#6  _M_destroy (__size=<optimized out>, this=0x7f33d4ff1620) at /usr/local/include/c++/6.2.0/bits/basic_string.h:186
#7  _M_dispose (this=0x7f33d4ff1620) at /usr/local/include/c++/6.2.0/bits/basic_string.h:181
#8  ~basic_string (this=0x7f33d4ff1620, __in_chrg=<optimized out>) at /usr/local/include/c++/6.2.0/bits/basic_string.h:558
#9  owt_base::RawTransport<(owt_base::Protocol)0>::writeHandler (this=0x2c35840, ec=..., bytes=0) at ../../../../core/owt_base/RawTransport.cpp:451
#10 0x00007f33ecee5a8a in operator() (a2=<optimized out>, a1=..., p=<optimized out>, this=<optimized out>) at /usr/include/boost/bind/mem_fn_template.hpp:280
#11 operator()<boost::_mfi::mf2<void, owt_base::RawTransport<(owt_base::Protocol)0u>, const boost::system::error_code&, long unsigned int>, boost::_bi::list2<const boost::system::error_code&, long unsigned int const&> > (a=<synthetic pointer>, f=..., this=0x7f33d4ff8c40) at /usr/include/boost/bind/bind.hpp:392
#12 operator()<boost::system::error_code, long unsigned int> (a2=@0x7f33d4ff8c28: 139860995053847, a1=..., this=0x7f33d4ff8c30) at /usr/include/boost/bind/bind_template.hpp:102
#13 boost::asio::detail::write_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, boost::_bi::bind_t<void, boost::_mfi::mf2<void, owt_base::RawTransport<(owt_base::Protocol)0>, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<owt_base::RawTransport<(owt_base::Protocol)0>*>, boost::arg<1> (*)(), boost::arg<2> (*)()> > >::operator() (this=this@entry=0x7f33d4ff8cf0, ec=..., 
    bytes_transferred=<optimized out>, start=start@entry=0) at /usr/include/boost/asio/impl/write.hpp:261
#14 0x00007f33ecee6334 in operator() (this=0x7f33d4ff8cf0) at /usr/include/boost/asio/detail/bind_handler.hpp:118
#15 asio_handler_invoke<boost::asio::detail::binder2<boost::asio::detail::write_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, boost::_bi::bind_t<void, boost::_mfi::mf2<void, owt_base::RawTransport<(owt_base::Protocol)0>, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<owt_base::RawTransport<(owt_base::Protocol)0>*>, boost::arg<1> (*)(), boost::arg<2> (*)()> > >, boost::system::error_code, unsigned long> > (
    function=<error reading variable: access outside bounds of object referenced via synthetic pointer>) at /usr/include/boost/asio/handler_invoke_hook.hpp:64
#16 invoke<boost::asio::detail::binder2<boost::asio::detail::write_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, boost::_bi::bind_t<void, boost::_mfi::mf2<void, owt_base::RawTransport<(owt_base::Protocol)0>, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<owt_base::RawTransport<(owt_base::Protocol)0>*>, boost::arg<1> (*)(), boost::arg<2> (*)()> > >, boost::system::error_code, unsigned long>, boost::_bi::bind_t<void, boost::_mfi::mf2<void, owt_base::RawTransport<(owt_base::Protocol)0>, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<owt_base::RawTransport<(owt_base::Protocol)0>*>, boost::arg<1> (*)(), boost::arg<2> (*)()> > > (context=..., function=...) at /usr/include/boost/asio/detail/handler_invoke_helpers.hpp:39
#17 asio_handler_invoke<boost::asio::detail::binder2<boost::asio::detail::write_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, boost::_bi::bind_t<void, boost::_mfi::mf2<void, owt_base::RawTransport<(owt_base::Protocol)0>, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi:---Type <return> to continue, or q <return> to quit---
:value<owt_base::RawTransport<(owt_base::Protocol)0>*>, boost::arg<1> (*)(), boost::arg<2> (*)()> > >, boost::system::error_code, unsigned long>, boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, boost::_bi::bind_t<void, boost::_mfi::mf2<void, owt_base::RawTransport<(owt_base::Protocol)0>, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<owt_base::RawTransport<(owt_base::Protocol)0>*>, boost::arg<1> (*)(), boost::arg<2> (*)()> > > (
    this_handler=0x7f33d4ff8ca0, function=...) at /usr/include/boost/asio/impl/write.hpp:533
#18 invoke<boost::asio::detail::binder2<boost::asio::detail::write_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, boost::_bi::bind_t<void, boost::_mfi::mf2<void, owt_base::RawTransport<(owt_base::Protocol)0>, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<owt_base::RawTransport<(owt_base::Protocol)0>*>, boost::arg<1> (*)(), boost::arg<2> (*)()> > >, boost::system::error_code, unsigned long>, boost::asio::detail::write_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, boost::_bi::bind_t<void, boost::_mfi::mf2<void, owt_base::RawTransport<(owt_base::Protocol)0>, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<owt_base::RawTransport<(owt_base::Protocol)0>*>, boost::arg<1> (*)(), boost::arg<2> (*)()> > > > (
    context=..., function=...) at /usr/include/boost/asio/detail/handler_invoke_helpers.hpp:39
#19 boost::asio::detail::reactive_socket_send_op<boost::asio::mutable_buffers_1, boost::asio::detail::write_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, boost::_bi::bind_t<void, boost::_mfi::mf2<void, owt_base::RawTransport<(owt_base::Protocol)0>, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<owt_base::RawTransport<(owt_base::Protocol)0>*>, boost::arg<1> (*)(), boost::arg<2> (*)()> > > >::do_complete (owner=0x2c0c910, base=0x7f33689bd830) at /usr/include/boost/asio/detail/reactive_socket_send_op.hpp:107
#20 0x00007f33ecedfd4b in complete (bytes_transferred=0, ec=..., owner=..., this=0x7f33689bd830) at /usr/include/boost/asio/detail/task_io_service_operation.hpp:37
#21 do_run_one (ec=..., this_thread=..., lock=..., this=0x2c0c910) at /usr/include/boost/asio/detail/impl/task_io_service.ipp:412
#22 boost::asio::detail::task_io_service::run (this=0x2c0c910, ec=...) at /usr/include/boost/asio/detail/impl/task_io_service.ipp:153
#23 0x00007f33ecee0d7f in boost::asio::io_service::run (this=0x2c358e8) at /usr/include/boost/asio/impl/io_service.ipp:59
#24 0x00007f33ed31d27a in thread_proxy () from /lib64/libboost_thread-mt.so.1.53.0
#25 0x00007f33fed65dc5 in start_thread () from /lib64/libpthread.so.0
#26 0x00007f33fea9476d in clone () from /lib64/libc.so.6
(gdb) f 9
#9  owt_base::RawTransport<(owt_base::Protocol)0>::writeHandler (this=0x2c35840, ec=..., bytes=0) at ../../../../core/owt_base/RawTransport.cpp:451
451	../../../../core/owt_base/RawTransport.cpp: No such file or directory.
(gdb) p ec
$1 = <optimized out>

**Comment by daijh** [comment]
@starwarfan 
Please have a look at RawTransport

**Comment by starwarfan** [comment]
Hi, can you provide detail steps to reproduce the issue?
