### ISSUE TITLE
videoTranscoder-sw.node Error

### ISSUE THREAD

**Issue by qq501157100** [open-webrtc-toolkit/owt-server#761]
* Checking modules...
Local network address:  IPv4=wlp5s0:192.168.1.36 
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aucodec: opus/48000/2
vidcodec: H264
vidcodec: H264
vidcodec: H264
vidcodec: H264
vidcodec: VP8
sipua is ready.
[PASS] logger.node
[PASS] internalIO.node
[PASS] mediaFrameMulticaster.node
[PASS] avstream.node
[PASS] audioMixer.node
[FAIL] videoTranscoder-sw.node Error: /home/morn/owt-server-43/owt-server/source/agent/video/videoTranscoder/videoTranscoder_sw/build/Release/videoTranscoder-sw.node: undefined symbol: _ZTVN6webrtc21TemporalLayersFactoryE
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at /home/morn/owt-server-43/owt-server/scripts/module_test.js:33:11
    at Array.map (<anonymous>)
    at /home/morn/owt-server-43/owt-server/scripts/module_test.js:31:10
    at ChildProcess.exithandler (child_process.js:273:7)
[FAIL] videoAnalyzer-sw.node Error: /home/morn/owt-server-43/owt-server/source/agent/video/videoTranscoder/videoAnalyzer_sw/build/Release/videoAnalyzer-sw.node: undefined symbol: _ZTVN6webrtc21TemporalLayersFactoryE
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at /home/morn/owt-server-43/owt-server/scripts/module_test.js:33:11
    at Array.map (<anonymous>)
    at /home/morn/owt-server-43/owt-server/scripts/module_test.js:31:10
    at ChildProcess.exithandler (child_process.js:273:7)
[FAIL] videoMixer-sw.node Error: /home/morn/owt-server-43/owt-server/source/agent/video/videoMixer/videoMixer_sw/build/Release/videoMixer-sw.node: undefined symbol: _ZTVN6webrtc21TemporalLayersFactoryE
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at /home/morn/owt-server-43/owt-server/scripts/module_test.js:33:11
    at Array.map (<anonymous>)
    at /home/morn/owt-server-43/owt-server/scripts/module_test.js:31:10
    at ChildProcess.exithandler (child_process.js:273:7)
[PASS] webrtc.node
[PASS] sipIn.node

**Comment by jwzhuang** [comment]
@qq501157100 How to fix it? 
I have the same problem.
