### ISSUE TITLE
 Error when mcu downloads webrtc dependency

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-server#805]
1，Environment and platform：
master，ubuntu18.04

2，Reproduce step：
      cd owt-server
      ./installDeps.sh --only webrtc
      error:
/home/webrtc/Workspace/masterbuildm79update/owt-se     [   <=>                                                                                                           ] 345.04K   380KB/s    in 0.9s    

2020-12-23 21:03:15 (380 KB/s) - ‘/home/webrtc/Workspace/masterbuildm79update/owt-server/third_party/webrtc/src/tools-woogeen/tmp/libyuv.2adb84e39e360723d19c68f315d99e3e0f88318c.tar.gz’ saved [353325]

patching file BUILD.gn
Generate ninja files
Traceback (most recent call last):
  File "/home/webrtc/Workspace/masterbuildm79update/owt-server/third_party/webrtc/src/tools-woogeen/tmp/depto_tools/gn.py", line 15, in <module>
    import gclient_utils
  File "/home/webrtc/Workspace/masterbuildm79update/owt-server/third_party/webrtc/src/tools-woogeen/tmp/depto_tools/gclient_utils.py", line 264
    except OSError, e:
                  ^
SyntaxError: invalid syntax
ninja: Entering directory `out'
ninja: fatal: chdir to 'out' - No such file or directory
find: ‘./out/obj/’: No such file or directory
Generate libwebrtc.a Fail
/home/webrtc/Workspace/masterbuildm79update/owt-server/third_party/webrtc
/home/webrtc/Workspace/masterbuildm79update/owt-server/scripts
depot_tools already installed.
src already exists.
Running depot tools as root is sad.
^Cncing projects:  94% (35/37) src/third_party/openh264/src                           
Allowed parallel jobs: 8

expected: 
 ./installDeps.sh --only webrtc
No error, normal download dependencies, normal compilation and packaging

**Comment by daijh** [comment]
python2 is required.

```bash
python -V
Python 2.7.17
```
