### ISSUE TITLE
getting index.js:204 server connection failed: Error: Joining room failed  at owt.js:9

### ISSUE THREAD

**Issue by anilk9096** [open-webrtc-toolkit/owt-server#891]
Set username and password for rabbitmq and mongodb while installing and after that did initauth.sh and given same username and password . 
getting this error in all nodes 
4.3.X github code build 

2021-01-22 09:45:55.270  - INFO: WorkingNode - pid: 104415
2021-01-22 09:45:55.275  - INFO: WorkingNode - Connecting to rabbitMQ server...
2021-01-22 09:45:55.332  - INFO: AmqpClient - Connecting to rabbitMQ server OK, options: { host: 'localhost', port: 5672, login: 'root' }
2021-01-22 09:45:55.356  - INFO: AmqpClient - Connection to rabbitMQ server error Error: libboost_thread-mt.so.1.53.0: cannot open shared obj$
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/Release-CentOS4.3.x/webrtc_agent/webrtc/wrtcConnection.js:6:19)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
2021-01-22 09:45:55.364  - INFO: AmqpClient - Connection to rabbitMQ server error { Error: read ECONNRESET
    at TCP.onread (net.js:622:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
2021-01-22 09:45:56.368  - INFO: AmqpClient - Connecting to rabbitMQ server OK, options: { host: 'localhost', port: 5672, login: 'root' }

**Comment by starwarfan** [comment]
Hi
Can you check the libboost version in your environment according to the error?

**Comment by anilk9096** [comment]
hi @starwarfan  
BOOST_VERSION 106501

BOOST_LIB_VERSION "1_65_1"

**Comment by anilk9096** [comment]
any update ?

**Comment by starwarfan** [comment]
Hi,
It seems that your build environment is boost1.53, but your runtime environment's boost may be 1.65. Please check.

**Comment by anilk9096** [comment]
did fresh build with same environment
