### ISSUE TITLE
owt-server subscribers disconnecting automatically after 5 times of subscription.

### ISSUE THREAD

**Issue by shivappl** [open-webrtc-toolkit/owt-server#910]
**owt-server MCU subscribing user 5 times continously at the 5th time all streams are disconnecting.** 

**Below are the errors i observed in debug mode**

     [Function] ],
  corrID: 2306,
  replyTo: 'amq.gen-_nBOUNn_eM7jscpMOyHz0A' }
2021-02-09 13:57:50.058  - ERROR: AmqpClient - Error processing call:  TypeError: Cannot read property 'closeMedia' of null
    at processOfferMedia (/home/pnap28074/owt-server/dist/webrtc_agent/webrtc/wrtcConnection.js:447:16)
    at processOffer (/home/pnap28074/owt-server/dist/webrtc_agent/webrtc/wrtcConnection.js:483:9)
    at processSignalling (/home/pnap28074/owt-server/dist/webrtc_agent/webrtc/wrtcConnection.js:595:9)
    at Object.that.onSignalling (/home/pnap28074/owt-server/dist/webrtc_agent/webrtc/wrtcConnection.js:604:7)
    at Object.that.onTransportSignaling (/home/pnap28074/owt-server/dist/webrtc_agent/webrtc/index.js:339:18)
    at /home/pnap28074/owt-server/dist/webrtc_agent/amqp_client.js:139:53
    at Message.<anonymous> (/home/pnap28074/owt-server/dist/webrtc_agent/node_modules/amqp/lib/queue.js:209:28)
    at Message.emit (events.js:198:13)
    at Queue._onContent (/home/pnap28074/owt-server/dist/webrtc_agent/node_modules/amqp/lib/queue.js:550:25)
    at AMQPParser.self.parser.onContent (/home/pnap28074/owt-server/dist/webrtc_agent/node_modules/amqp/lib/connection.js:142:32)
(node:25062) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated

******Below is in info mode.******

2021-02-09 13:46:25,549  - WARN: LibNiceConnection - id: 95fef6205d694c28b427491f6d2bc743,  message: component failed, ice_config_.transport_name: video, componentId: 1
2021-02-09 13:46:25,549  - WARN: IceConnection - id: 95fef6205d694c28b427491f6d2bc743,  message: Ice Failed
2021-02-09 13:46:25,550  - ERROR: WebRtcConnection - id: 95fef6205d694c28b427491f6d2bc743,  message: Transport Failed, transportType: video
2021-02-09 13:46:25.562  - WARN: Connection - message: failed the ICE process, code: 502, id: 95fef6205d694c28b427491f6d2bc743
2021-02-09 13:46:25.562  - WARN: WrtcConnection - ICE failed,  500 95fef6205d694c28b427491f6d2bc743
2021-02-09 13:46:25,575  - WARN: IceConnection - id: 95fef6205d694c28b427491f6d2bc743,  message: unexpected ice state transition, iceState: failed,  newIceState: finished
2021-02-09 13:46:25,575  - WARN: IceConnection - id: 95fef6205d694c28b427491f6d2bc743,  message: unexpected ice state transition, iceState: failed,  newIceState: finished
2021-02-09 13:46:40.804  - INFO: Connections - Connection does NOT exist:95fef6205d694c28b427491f6d2bc743
2021-02-09 13:46:40.860  - INFO: Connections - Connection does NOT exist:b9b1283141124357a4d669323d456c34
2021-02-09 13:46:40.862  - INFO: Connections - Connection does NOT exist:9c826cebc5e54b738718e837e4df48f1
2021-02-09 13:46:40.864  - INFO: Connections - Connection does NOT exist:072bc6abd3ae44a3945d2270f66ad2a5
2021-02-09 13:46:40.865  - INFO: Connections - Connection does NOT exist:1576d44b74c8402ebb83cedd912c68a0
2021-02-09 13:46:40.866  - INFO: Connections - Connection does NOT exist:d4a097e1551a487a8adbd0413a85f76c
2021-02-09 13:47:21.726  - WARN: WrtcConnection - MID 2 in offer has no mapped operations (disabled)
2021-02-09 13:47:21.727  - WARN: WrtcConnection - MID 3 in offer has no mapped operations (disabled)###

**Comment by andreasunterhuber** [comment]
@shivappl which version/commit do you use?

**Comment by shivappl** [comment]
@andreasunterhuber i used master branch
