### ISSUE TITLE
can not build in wsl2

### ISSUE THREAD

**Issue by afei00615** [open-webrtc-toolkit/owt-server#943]
I build owt-server 4.3.x branch in wsl2,but some error happen,message:
../conn_handler/WoogeenHandler.cpp:30:7: error: ‘redheader’ was not declared in this scope
       redheader* redhead = (redheader*)(buf + h->getHeaderLength());
       ^~~~~~~~~
../conn_handler/WoogeenHandler.cpp:30:7: note: suggested alternative: ‘RedHeader’
       redheader* redhead = (redheader*)(buf + h->getHeaderLength());
       ^~~~~~~~~
       RedHeader
../conn_handler/WoogeenHandler.cpp:30:18: error: ‘redhead’ was not declared in this scope
       redheader* redhead = (redheader*)(buf + h->getHeaderLength());
                  ^~~~~~~
../conn_handler/WoogeenHandler.cpp:30:18: note: suggested alternative: ‘readahead’
       redheader* redhead = (redheader*)(buf + h->getHeaderLength());
                  ^~~~~~~
                  readahead
../conn_handler/WoogeenHandler.cpp:30:39: error: expected primary-expression before ‘)’ token
       redheader* redhead = (redheader*)(buf + h->getHeaderLength());
                                       ^
../conn_handler/WoogeenHandler.cpp: In member function ‘virtual void erizo::WoogeenHandler::write(erizo::Handler::Context*, std::shared_ptr<erizo::DataPacket>)’:
../conn_handler/WoogeenHandler.cpp:56:7: error: ‘redheader’ was not declared in this scope
       redheader *redhead = (redheader*) (buf + totalLength);
       ^~~~~~~~~
../conn_handler/WoogeenHandler.cpp:56:7: note: suggested alternative: ‘RedHeader’
       redheader *redhead = (redheader*) (buf + totalLength);
       ^~~~~~~~~
       RedHeader
../conn_handler/WoogeenHandler.cpp:56:18: error: ‘redhead’ was not declared in this scope
       redheader *redhead = (redheader*) (buf + totalLength);
                  ^~~~~~~
../conn_handler/WoogeenHandler.cpp:56:18: note: suggested alternative: ‘readahead’
       redheader *redhead = (redheader*) (buf + totalLength);
                  ^~~~~~~
                  readahead
../conn_handler/WoogeenHandler.cpp:56:39: error: expected primary-expression before ‘)’ token
       redheader *redhead = (redheader*) (buf + totalLength);
                                       ^
../conn_handler/WoogeenHandler.cpp:62:32: error: expected primary-expression before ‘)’ token
           redhead = (redheader*) (buf + totalLength);
                                ^
../conn_handler/WoogeenHandler.cpp:73:9: error: ‘RTPHeader’ was not declared in this scope
         RTPHeader* mediahead = (RTPHeader*) deliverMediaBuffer;
         ^~~~~~~~~
../conn_handler/WoogeenHandler.cpp:73:9: note: suggested alternative: ‘RedHeader’
         RTPHeader* mediahead = (RTPHeader*) deliverMediaBuffer;
         ^~~~~~~~~
         RedHeader
../conn_handler/WoogeenHandler.cpp:73:20: error: ‘mediahead’ was not declared in this scope
         RTPHeader* mediahead = (RTPHeader*) deliverMediaBuffer;
                    ^~~~~~~~~
../conn_handler/WoogeenHandler.cpp:73:20: note: suggested alternative: ‘readahead’
         RTPHeader* mediahead = (RTPHeader*) deliverMediaBuffer;
                    ^~~~~~~~~
                    readahead
../conn_handler/WoogeenHandler.cpp:73:43: error: expected primary-expression before ‘)’ token
         RTPHeader* mediahead = (RTPHeader*) deliverMediaBuffer;
                                           ^
rtcConn.target.mk:197: recipe for target 'Release/obj.target/rtcConn/conn_handler/WoogeenHandler.o' failed
make: *** [Release/obj.target/rtcConn/conn_handler/WoogeenHandler.o] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory '/mnt/e/owt/owt-server/source/agent/webrtc/rtcConn/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/yanfeijun/.nvm/versions/node/v10.21.0/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.72-microsoft-standard-WSL2
gyp ERR! command "/home/yanfeijun/.nvm/versions/node/v10.21.0/bin/node" "/home/yanfeijun/.nvm/versions/node/v10.21.0/bin/node-gyp" "build" "-j" "4" "--loglevel=error"
gyp ERR! cwd /mnt/e/owt/owt-server/source/agent/webrtc/rtcConn
gyp ERR! node -v v10.21.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
child_process.js:669
    throw err;
    ^

Error: Command failed: node-gyp build -j 4 --loglevel=error
    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at buildTarget (/mnt/e/owt/owt-server/scripts/build.js:133:5)
    at buildList.map (/mnt/e/owt/owt-server/scripts/build.js:161:10)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/mnt/e/owt/owt-server/scripts/build.js:156:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

**Comment by HeiSir2014** [comment]
You need to modify this file to solve this bug.
File: source\agent\webrtc\rtcConn\conn_handler\WoogeenHandler.cpp
```CPP
#include "WoogeenHandler.h"
#include "MediaStream.h"
#include <rtputils.h>
```
changed to
```CPP
#include "WoogeenHandler.h"
#include "MediaStream.h"

// owt-server/third_party/licode/erizo/src/erizo/rtp/RtpUtils.h

#include "../erizo/src/erizo/rtp/RtpUtils.h"

// owt-server/source/core/common/rtputils.h
#include "../../../../core/common/rtputils.h"
```

**Comment by afei00615** [comment]
> **You need to modify this file to solve this bug.**
> _File: source\agent\webrtc\rtcConn\conn_handler\WoogeenHandler.cpp_
> 
> ```c++
> #include "WoogeenHandler.h"
> #include "MediaStream.h"
> #include <rtputils.h>
> ```
> 
> changed to
> 
> ```c++
> #include "WoogeenHandler.h"
> #include "MediaStream.h"
> 
> // owt-server/third_party/licode/erizo/src/erizo/rtp/RtpUtils.h
> #include "../erizo/src/erizo/rtp/RtpUtils.h"
> 
> // owt-server/source/core/common/rtputils.h
> #include "../../../../core/common/rtputils.h"
> ```

thanks，I also modify those file：
![image](https://user-images.githubusercontent.com/3326560/115681871-8445a000-a387-11eb-93ca-1ba243419cd5.png)

**Comment by afei00615** [comment]
> **You need to modify this file to solve this bug.**
> _File: source\agent\webrtc\rtcConn\conn_handler\WoogeenHandler.cpp_
> 
> ```c++
> #include "WoogeenHandler.h"
> #include "MediaStream.h"
> #include <rtputils.h>
> ```
> 
> changed to
> 
> ```c++
> #include "WoogeenHandler.h"
> #include "MediaStream.h"
> 
> // owt-server/third_party/licode/erizo/src/erizo/rtp/RtpUtils.h
> #include "../erizo/src/erizo/rtp/RtpUtils.h"
> 
> // owt-server/source/core/common/rtputils.h
> #include "../../../../core/common/rtputils.h"
> ```

thanks ，i also modify those file：
	        modified:   source/agent/webrtc/webrtcLib/conn_handler/WoogeenHandler.cpp
	        modified:   source/core/owt_base/AudioFrameConstructor.cpp
	        modified:   source/core/owt_base/AudioUtilities.cpp
        modified:   source/core/owt_base/WebRTCTransport.h
