### ISSUE TITLE
Docker error in start services 

### ISSUE THREAD

**Issue by anilk9096** [open-webrtc-toolkit/owt-server#981]
HI,

After success build docker containers both with source and with out , starting image and entering into bash was good , when starting services in build and run both containers giving following error in cluster node start 

021-04-22 07:06:19.326  - WARN: AmqpClient - Connecting error: { Error: connect ECONNREFUSED 127.0.0.1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  cause:
   { Error: connect ECONNREFUSED 127.0.0.1:5672
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
     errno: 'ECONNREFUSED',
     code: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 5672 },

Cluster node log : 

2021-04-22 14:35:43.701  - INFO: ClusterManager - Run as slave.
2021-04-22 14:35:43.701  - INFO: ClusterManager - Someone else became master.
2021-04-22 14:35:43.701  - INFO: ClusterManager - Run as slave.
2021-04-22 14:35:43.703  - INFO: ClusterManager - Cluster manager is in service as master!
2021-04-22 14:35:43.704  - INFO: ClusterManager - Cluster manager is in service as master!
2021-04-22 14:35:43.706  - INFO: ClusterManager - Cluster manager is in service as master!
2021-04-22 14:35:43.708  - INFO: ClusterManager - Cluster manager is in service as master!
2021-04-22 14:35:43.722  - INFO: ClusterManager - Lose heart-beat from master.
2021-04-22 14:35:43.722  - INFO: ClusterManager - Run as candidate.
2021-04-22 14:35:43.729  - ERROR: ClusterManager - !!Double master!! self: 144145397 another: 969215517
2021-04-22 14:35:43.729  - ERROR: ClusterManager - Another master is more senior than me, I quit.
2021-04-22 14:35:43.729  - WARN: Main - Exiting on SIGINT
2021-04-22 14:35:45.970  - INFO: Main - Process exit

**Comment by andreasunterhuber** [comment]
@anilk9096 it seems that your local RabbitMQ was not started. Therefore the system can't setup probably. Start RabbitMQ before in your docker image or point in the config files (.toml) to an external RabbitMQ. If you start more docker images (cluster mode), you have to use ONE/the same (!) RabbitMQ for all docker images.
