### ISSUE TITLE
AmqpClient - Connecting error

### ISSUE THREAD

**Issue by tianhaoyang-thy** [open-webrtc-toolkit/owt-server#982]
I have deploy the own-server successfully, its working fine . But today when I run (./bin/init-all.sh --deps && ./bin/start-all.sh) the server in docker container. I got errors like that:

starting management-api, stdout -> /home/workspace/owt-server/dist/logs/management-api.stdout
(node:1388171) DeprecationWarning: Mongoose: `findOneAndUpdate()` and `findOneAndDelete()` without the `useFindAndModify` option set to false are deprecated. See: https://mongoosejs.com/docs/deprecations.html#findandmodify
starting cluster-manager, stdout -> /home/workspace/owt-server/dist/logs/cluster-manager.stdout
2021-04-25 07:26:46.223  - WARN: AmqpClient - Connecting error: { Error: Handshake terminated by server: 403 (ACCESS-REFUSED) with message "ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile."
    at afterStartOk (/home/workspace/owt-server/dist/cluster_manager/node_modules/amqplib/lib/connection.js:220:12)
    at /home/workspace/owt-server/dist/cluster_manager/node_modules/amqplib/lib/connection.js:160:12
    at Socket.recv (/home/workspace/owt-server/dist/cluster_manager/node_modules/amqplib/lib/connection.js:499:12)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:555:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  cause:
   Error: Handshake terminated by server: 403 (ACCESS-REFUSED) with message "ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile."

**Comment by starwarfan** [comment]
Do you save rabbitmq username/password settings? Or do you connect rabbitmq from non-localhost using default account?

**Comment by tianhaoyang-thy** [comment]
> Do you save rabbitmq username/password settings? Or do you connect rabbitmq from non-localhost using default account?
I haven't modified or saved some settings about mq manully. And I have uninstall the rabbitmq-server from local, then install it again. the errors still be there.

**Comment by tianhaoyang-thy** [comment]
ohh. I find the files that stores the auth info of rabbitmq. After I deleted its, the server works. we can search them by 'cd dist; find ./ -name .owt.authstore' .

**Comment by tianhaoyang-thy** [comment]
ohh. I find the files that stores the auth info of rabbitmq. After I deleted its, the server works. we can search them by 'cd dist; find ./ -name .owt.authstore' .
