### ISSUE TITLE
scripts/build.js -t all --check error with newst intel media-sdk

### ISSUE THREAD

**Issue by dannyZhou** [open-webrtc-toolkit/owt-server#985]
# Environment: 
OS: `DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"`
intel media sdk version: e147bfcb5f24f3baed9af141851d3e3cde9148d4

# Question1: 

```
make: Leaving directory '/home/danny/sdb1/owt/owt-server/source/agent/video/videoMixer/videoMixer_msdk/build'
Finish addon - video-mixer-msdk
Building addon - video-transcoder-msdk
make: Entering directory '/home/danny/sdb1/owt/owt-server/source/agent/video/videoTranscoder/videoTranscoder_msdk/build'
  CXX(target) Release/obj.target/videoTranscoder-msdk/../addon.o
  CXX(target) Release/obj.target/videoTranscoder-msdk/../VideoTranscoderWrapper.o
  CXX(target) Release/obj.target/videoTranscoder-msdk/../../../../core/owt_base/MsdkFrameEncoder.o
  CXX(target) Release/obj.target/videoTranscoder-msdk/../../../../core/owt_base/MsdkBase.o
In file included from ../../VideoTranscoderWrapper.cpp:9:0:
../../VideoTranscoderWrapper.h:13:10: fatal error: nan.h: No such file or directory
 #include <nan.h>
          ^~~~~~~
compilation terminated.
In file included from ../../addon.cc:5:0:
../../VideoTranscoderWrapper.h:13:10: fatal error: nan.h: No such file or directory
 #include <nan.h>
          ^~~~~~~
compilation terminated.
videoTranscoder-msdk.target.mk:150: recipe for target 'Release/obj.target/videoTranscoder-msdk/../VideoTranscoderWrapper.o' failed
make: *** [Release/obj.target/videoTranscoder-msdk/../VideoTranscoderWrapper.o] Error 1
make: *** Waiting for unfinished jobs....
videoTranscoder-msdk.target.mk:153: recipe for target 'Release/obj.target/videoTranscoder-msdk/../addon.o' failed
make: *** [Release/obj.target/videoTranscoder-msdk/../addon.o] Error 1
make: Leaving directory '/home/danny/sdb1/owt/owt-server/source/agent/video/videoTranscoder/videoTranscoder_msdk/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/danny/.nvm/versions/node/v10.21.0/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0-42-generic
gyp ERR! command "/home/danny/.nvm/versions/node/v10.21.0/bin/node" "/home/danny/.nvm/versions/node/v10.21.0/bin/node-gyp" "build" "-j" "4" "--loglevel=error"
gyp ERR! cwd /home/danny/sdb1/owt/owt-server/source/agent/video/videoTranscoder/videoTranscoder_msdk
gyp ERR! node -v v10.21.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
child_process.js:669
    throw err;
    ^

Error: Command failed: node-gyp build -j 4 --loglevel=error
    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at buildTarget (/home/danny/sdb1/owt/owt-server/scripts/build.js:149:5)
    at buildList.map (/home/danny/sdb1/owt/owt-server/scripts/build.js:177:10)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/home/danny/sdb1/owt/owt-server/scripts/build.js:172:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

```

## Question1 solution: 
```diff
diff --git a/source/agent/video/videoTranscoder/videoTranscoder_msdk/binding.msdk.gyp b/source/agent/video/videoTranscoder/videoTranscoder_msdk/binding.msdk.gyp
index 9a8ef32b..2081d407 100644
--- a/source/agent/video/videoTranscoder/videoTranscoder_msdk/binding.msdk.gyp
+++ b/source/agent/video/videoTranscoder/videoTranscoder_msdk/binding.msdk.gyp
@@ -36,6 +36,7 @@
         '-fno-exceptions',
     ],
     'include_dirs': [ '..',
+                      "<!(node -e \"require('nan')\")",
                       '$(CORE_HOME)/common',
                       '$(CORE_HOME)/owt_base',
                       '$(CORE_HOME)/../../third_party/webrtc/src',

```

# Question2:

```
gyp info spawn args [ 'V=1', 'BUILDTYPE=Debug', '-C', 'build', '--jobs', 4 ]
make: Entering directory '/home/danny/sdb1/owt/owt-server/source/agent/video/videoMixer/videoMixer_msdk/build'
  g++ -shared -pthread -rdynamic -m64 -z noexecstack -z relro -Wl,-soname=videoMixer-msdk.node -o Debug/obj.target/videoMixer-msdk.node -Wl,--start-group Debug/obj.target/videoMixer-msdk/../addon.o Debug/obj.target/videoMixer-msdk/../VideoMixerWrapper.o Debug/obj.target/videoMixer-msdk/../MsdkVideoCompositor.o Debug/obj.target/videoMixer-msdk/../VideoMixer.o Debug/obj.target/videoMixer-msdk/../../../../core/owt_base/I420BufferManager.o Debug/obj.target/videoMixer-msdk/../../../../core/owt_base/MediaFramePipeline.o Debug/obj.target/videoMixer-msdk/../../../../core/owt_base/FrameConverter.o Debug/obj.target/videoMixer-msdk/../../../../core/owt_base/VCMFrameDecoder.o Debug/obj.target/videoMixer-msdk/../../../../core/owt_base/VCMFrameEncoder.o Debug/obj.target/videoMixer-msdk/../../../../core/owt_base/FFmpegFrameDecoder.o Debug/obj.target/videoMixer-msdk/../../../../core/owt_base/MsdkFrameDecoder.o Debug/obj.target/videoMixer-msdk/../../../../core/owt_base/MsdkFrameEncoder.o Debug/obj.target/videoMixer-msdk/../../../../core/owt_base/MsdkBase.o Debug/obj.target/videoMixer-msdk/../../../../core/owt_base/MsdkFrame.o Debug/obj.target/videoMixer-msdk/../../../../core/owt_base/MsdkScaler.o Debug/obj.target/videoMixer-msdk/../../../../core/owt_base/FastCopy.o Debug/obj.target/videoMixer-msdk/../../../../core/common/JobTimer.o Debug/obj.target/videoMixer-msdk/../../../../../third_party/mediasdk/samples/sample_common/src/base_allocator.o Debug/obj.target/videoMixer-msdk/../../../../../third_party/mediasdk/samples/sample_common/src/vaapi_allocator.o -Wl,--end-group -lboost_thread -llog4cxx -L/home/danny/sdb1/owt/owt-server/source/core/../../third_party/webrtc -lwebrtc -L/home/danny/sdb1/owt/owt-server/source/core/../../third_party/openh264 -lopenh264 -L/opt/intel/mediasdk/lib64 -lmfx -lva -lva-drm -L/home/danny/sdb1/owt/owt-server/./scripts/../build/libdeps/build//lib -lavutil -lavcodec -lavformat
/usr/bin/ld: cannot find -lmfx
collect2: error: ld returned 1 exit status
videoMixer-msdk.target.mk:200: recipe for target 'Debug/obj.target/videoMixer-msdk.node' failed
make: *** [Debug/obj.target/videoMixer-msdk.node] Error 1
make: Leaving directory '/home/danny/sdb1/owt/owt-server/source/agent/video/videoMixer/videoMixer_msdk/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/danny/.nvm/versions/node/v10.21.0/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0-42-generic
gyp ERR! command "/home/danny/.nvm/versions/node/v10.21.0/bin/node" "/home/danny/.nvm/versions/node/v10.21.0/bin/node-gyp" "build" "-j" "4" "--loglevel=verbose" "--debug"
gyp ERR! cwd /home/danny/sdb1/owt/owt-server/source/agent/video/videoMixer/videoMixer_msdk
gyp ERR! node -v v10.21.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
child_process.js:669
    throw err;
    ^

Error: Command failed: node-gyp build -j 4 --loglevel=verbose --debug
    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at buildTarget (/home/danny/sdb1/owt/owt-server/scripts/build.js:149:5)
    at buildList.map (/home/danny/sdb1/owt/owt-server/scripts/build.js:177:10)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/home/danny/sdb1/owt/owt-server/scripts/build.js:172:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
```

# question2 solution 
```shell 
sudo cp -a /opt/intel/mediasdk/lib /opt/intel/mediasdk/lib64
```

**Comment by dannyZhou** [comment]
@starwarfan Please check question2 and create pull request if need. Then close this issue. Thank you. 

Question1 and solution has in this pull request created by daijh.  https://github.com/open-webrtc-toolkit/owt-server/pull/996 

Thank you.
